### ISSUE TITLE
abrt-xorg: watch journal instead of /var/log/Xorg.0.log

### ISSUE THREAD

**Issue by mchalupa** [abrt/abrt#1023]
gnome-session now redirects logs of Xorg (or Xwayland) to journal, so abrt-xorg service is not working anymore.

How to artificially generate the backtrace in journal:
  1) log into gnome-shell under wayland (either from gdm or switch tty and run gnome-session --session=gnome-wayland)
  2) kill -SEGV xwayland_pid

**Comment by jfilak** [comment]
We have to port ```abrt-dump-xorg``` to ```journal```. Basically we need to do the same like we did with ```abrt-dump-oops```, where a new tool watching journal and creating problem directories has been developed (```abrt-dump-journal-oops```).
