### ISSUE TITLE
785 bugs in ABRT that can't be reported

### ISSUE THREAD

**Issue by sudhirkhanger** [abrt/abrt#1058]
ABRT has reported 785 bugs that can't be reported. They have polluted the UI and I have had to see 785 notifications.

    mce: [Hardware Error]: Machine check events logged

This error is probably due to excessive heating on my system which unfortunately is out of my control. UI and notification should be improved to either ignore or better place these bug entries that they don't pollute the whole UI.

![snapshot165](https://cloud.githubusercontent.com/assets/841656/10385853/9a2faba0-6e6c-11e5-991d-06446ef76ae0.png)

**Comment by sorki** [comment]
Already reported: #889, #943

As a workaround you can make ABRT ignore non-fatal MCE's like thermal warnings by setting

``OnlyFatalMCE = yes``

in

``/etc/abrt/plugins/oops.conf``

Closing as duplicate.
