### ISSUE TITLE
kernel.core_pattern being set in abrt-hook-ccpp.c ?

### ISSUE THREAD

**Issue by mrbriancollins** [abrt/abrt#1080]
I am trying to setup a remote abrt server for systems on my network to dump to. I noticed the kernel.core_pattern does not contain the %h value and could find no location to set this value. It looks as if it is set in abrt-hook-ccpp.c? Is there a way to change this in a config file?

**Comment by jfilak** [comment]
You do not need to specify '%h' in the core pattern. The problem directories should contain the file hostname by default.

Are you going to use Centralized Crash Collection configuration [1] or your own architecture?

1: http://abrt.readthedocs.org/en/latest/admin.html#configuring-centralized-crash-collection

**Comment by mrbriancollins** [comment]
was planning on using Centralized Crash Collection configuration. Just
didn't see it mentioned on how it would lay out.
Thank you for your response.

Brian

**Comment by jfilak** [comment]
I am closing this issue but please feel free to ask more question if you have any.
