### ISSUE TITLE
Support coredumpctl out-of-the-box

### ISSUE THREAD

**Issue by mcatanzaro** [abrt/abrt#1108]
Currently to get coredumpctl support, users must manually disable abrt-ccpp.service and enable abrt-journal-core.service. We would like to see coredumpctl integration enabled out of the box in Fedora Workstation, with zero setup, as it is a mature, killer feature for developers and it's a shame we still ship with it disabled.

I'm aware that abrt-journal-core.service currently implies that two copies of core dumps will be kept on the system (one by systemd and one by abrt). This is not ideal, but I think it's an acceptable cost, so long as there's a plan to fix it in the long term. I am uncertain what other benefits there are to abrt-ccpp.service.

**Comment by jfilak** [comment]
Hi Michael,

There is nothing that needs to be done on ABRT side. You just need update Fedora presets:
https://fedoraproject.org/wiki/Packaging:DefaultServices?rd=Starting_services_by_default
https://pagure.io/fedora-release/blob/master/f/80-workstation.preset

These are the features that you will lose:
https://github.com/abrt/abrt/wiki/CCpp-plugin

Can you please write a short list of features that you are missing in the current ABRT C/C++ plugin?

**Comment by mcatanzaro** [comment]
The only feature I'm missing is coredumpctl integration. :) Now that I've switched to abrt-journal-core.service, I'm a happy camper. I'd like to get this out to all our users by default.

If you think it's OK to do so, then I'll request for this to be changed in fedora-release.

**Comment by jfilak** [comment]
I just don't think it is necessary. I would rather make abrt as user friendly as coredumctl. abrt is not only about core dumps, it handles also uncaught Python and Java exceptions and Kernel oopses and we plan more in future.

So I would like to know why you prefer coredumctl over abrt?

**Comment by mcatanzaro** [comment]
I would prefer the upstream tool, which is available in basically all distros by virtue of being part of systemd, simply so that users don't have to learn Fedora-specific coredump handling. Also, we have coredumpctl installed by default, but it's useless by default, which isn't nice.

It does seem like a nicer tool as well. A couple immediate impressions from trying `abrt-cli` (which I do not normally use):

 * `coredumpctl` runs much faster than `abrt-cli ls`
 * `coredumpctl` has a nicer compressed output format than `abrt-cli ls` (showing 
 * `coredumpctl` can easily recall truncated traces from the journal long after it has deleted the full coredump.
 * `coredumpctl gdb` is ludicrously convenient.

Honestly, coredumpctl is REALLY nice and it's going to be hard to compete with it. I -- frankly -- would recommend to focus on the bug reporting experience, something coredumpctl does not do, rather than trying to compete with coredumpctl as a cli tool. (But that's just my impression!)

**Comment by xsuchy** [comment]
As of Fedora 26, ABRT will use coredumpctl by default.
