### ISSUE TITLE
abrt-hook-ccpp[13948]: /var/spool/abrt is 4876174163 bytes (more than 1279MiB), deleting 'ccpp-2016-04-19-07:59:15-32448'

### ISSUE THREAD

**Issue by brianjmurrell** [abrt/abrt#1132]
Xorg crashes.  The coredump file is massive.  >4GB.  abrt captures it, but then comes along some kind of garbage collector and removes it before is can be reported with:

```
Apr 19 08:29:48 pc.interlinx.bc.ca abrt-hook-ccpp[13948]: /var/spool/abrt is 4876174163 bytes (more than 1279MiB), deleting 'ccpp-2016-04-19-07:59:15-32448'
Apr 19 08:29:48 pc.interlinx.bc.ca abrt-server[14386]: Lock file '/var/spool/abrt/post-create.lock' is locked by process 13949
Apr 19 08:29:49 pc.interlinx.bc.ca abrt-server[13947]: Lock file '.lock' is locked by process 13948
Apr 19 08:29:49 pc.interlinx.bc.ca abrt-server[14386]: Lock file '/var/spool/abrt/post-create.lock' is locked by process 13949
Apr 19 08:29:49 pc.interlinx.bc.ca abrt-server[13947]: Lock file '.lock' is locked by process 13948
Apr 19 08:29:50 pc.interlinx.bc.ca abrt-server[13947]: Lock file '.lock' is locked by process 13948
Apr 19 08:29:50 pc.interlinx.bc.ca abrt-server[14386]: Lock file '/var/spool/abrt/post-create.lock' is locked by process 13949
Apr 19 08:29:51 pc.interlinx.bc.ca abrt-hook-ccpp[13948]: Can't remove directory '/var/spool/abrt/ccpp-2016-04-19-07:59:15-32448': Directory not empty
Apr 19 08:29:51 pc.interlinx.bc.ca abrt-server[13947]: '/var/spool/abrt/ccpp-2016-04-19-07:59:15-32448' is not a problem directory
Apr 19 08:29:51 pc.interlinx.bc.ca abrt-server[14386]: Lock file '/var/spool/abrt/post-create.lock' is locked by process 13949
Apr 19 08:29:51 pc.interlinx.bc.ca abrt-server[13947]: '/var/spool/abrt/ccpp-2016-04-19-07:59:15-32448' is not a problem directory
Apr 19 08:29:52 pc.interlinx.bc.ca abrt-server[13947]: '/var/spool/abrt/ccpp-2016-04-19-07:59:15-32448' is not a problem directory
Apr 19 08:29:52 pc.interlinx.bc.ca abrt-server[13947]: Deleting problem directory '/var/spool/abrt/ccpp-2016-04-19-07:59:15-32448'
Apr 19 08:29:52 pc.interlinx.bc.ca abrt-server[13947]: '/var/spool/abrt/ccpp-2016-04-19-07:59:15-32448' is not a problem directory
```

So it seems like we have competing components.  One is trying to create an abrt dump and one is trying to clean up big dumps before the other is even complete.

Is there even somewhere where this "1279MiB" threshold can be set so that I can at least get the coredump and report the segfault next time?

**Comment by jfilak** [comment]
Thank you for the report. You can increase the limit in the `/etc/abrt/abrt.conf` file (the option `MaxCrashReportsSize`).

I think we should increase the default limit which is `1GB` because crashes of `gnome-shell` often consume more disk space than the limit. However, I would be conservative and update the limit to 3GB because >4GB seems to be a too much demanding (subjective feeling).

**Comment by xsuchy** [comment]
@brianjmurrell as Jakub stated, you should raise your limit. If the 4GB core dump was really created then it is (another) bug as it should not be created in first place. But since we moved to coredumpctl, this should not happen in future.
