### ISSUE TITLE
Missing deps on EL6

### ISSUE THREAD

**Issue by sorki** [abrt/abrt#1134]
abrt: detected unhandled Python exception in '/usr/bin/abrt-action-notify'
abrt-server[990740]: Not saving repeating crash in '/usr/bin/abrt-action-notify'
abrtd: Traceback (most recent call last):
abrtd:   File "/usr/bin/abrt-action-notify", line 18, in <module>
abrtd:     from argparse import ArgumentParser
abrtd: ImportError: No module named argparse

**Comment by mhabrnal** [comment]
This should be fixed in rhel6.8
https://bugzilla.redhat.com/show_bug.cgi?id=1246539

**Comment by sorki** [comment]
Nice. Thanks.
