### ISSUE TITLE
abrt-action-install-debuginfo deletes files from "/"

### ISSUE THREAD

**Issue by kthrift** [abrt/abrt#1135]
I had something crash on me the other day and I went to generate a backtrace with abrt. It seemed to take longer than usual, so I worked on something else and maybe 10 minutes later, once I noticed the machine felt a little sluggish, I came back to look at what abrt was doing.  

I found it was deleting files from **"/"** -- a fairly significant negative side effect that was completely unexpected (I mean really ... attempting to submit a bug report suddenly causes files to be deleted from the root file system?!).

Here is the output from `ps -o user,cmd | fgrep abrt-action-trim-files`  showing the process doing the actual deletion:

> abrt     abrt-action-trim-files -f 4096m:/ -- //usr/lib/debug/.build-id/17/87e030bb7c3878dfda2f910a4ccc56c9deef18.debug ... ... ... /path/to/many/.debug

you'll notice the **-f 4096m:/** argument to abrt-action-trim-files, that **"/"** is supposed to be the first debug info cache directory in a list of debuginfo cache directories.  Clearly doing an **"rm -rf /"** is not the desired behavior.

Unfortunately, when the config option key, **DebuginfoLocation**, is set in _CCpp.conf_, then lines 146-152 of `abrt-action-install-debuginfo` end up initializing `cachedirs` to a string value "/var/cache/abrt-di" instead of the list type ["/var/cache/abrt-di"]:
`conf = problem.load_plugin_conf_file("CCpp.conf")`
`cachedirs = conf.get("DebuginfoLocation", None)`
Then, later on line 189, when building the command line arguments to `abrt-action-trim-files`, the code takes the first index of `cachedirs`.  When `cachedirs` is a string type whose value is an absolute directory path, taking the first index(`cachedirs[0]`), yields **"/"** instead of the first directory entry in a list:
`argv = ["abrt-action-trim-files", "-f", "%um:%s" % (size_mb, cachedirs[0]), "--"]`

So, not only is `abrt-action-trim-files` instructed to delete from **"/"**, but it is also only given a single cache directory to clean up, when supposedly there can be multiple cache directories specified -- that is the whole reason `cachedirs` is supposed to be a list in the first place!

**Comment by jfilak** [comment]
I am terribly sorry for that. I hope you didn't run the tool from command line as root and I hope it haven't deleted any file (in the most common workflow, the tool should run under the abrt user which can remove files only from the /var/cache/abrt-di directory).

We will fix this as soon as possible. The bug has been introduced by me when I was porting the tool to new configuration files. I didn't notice `cachedirs` is supposed to be a list because it doesn't make sense as all other ABRT tools work only with a single directory.
