### ISSUE TITLE
Support for large applications

### ISSUE THREAD

**Issue by avikivity** [abrt/abrt#1145]
Ref scylladb/scylla#892, scylladb/scylla#784, scylladb/scylla#762. @syuu1228.

ScyllaDB is a large C++ application that uses all of a machine's memory.  That means we typically have 120GB RSS, often 250GB, and in the future we'll probably see 2TB+.

If Scylla crashes, and abrt is installed, it will process the core.  Unfortunately with large RSS this takes a really long time. During that time there is no indication in the logs that something is going on.  While the processing is going on, the process cannot be restarted; and since it is part of a high availability cluster, this impacts availability.

Right now we have a Conflicts: abrt in our .rpm, but we'd like to play nicer than that.  Please considering improving the support for large applications.

**Comment by jfilak** [comment]
You can turn off saving core files and let abrt to generate backtrace from the crashed process. See 'SaveFullCore' in the /etc/abrt/plugins/CCpp.conf file for more details.

We can add ScyllaDB file system paths to 'IgnoredPaths' in the /etc/abrt/plugins/CCpp.conf file if you wish. abrt-hook-ccpp will ignore its crashes completely then.

Anyway, abrt-hook-ccpp must start honouring  the value of MaxCrashSize option from the /etc/abrt/abrt.conf file when writing core dump file.

**Comment by avikivity** [comment]
Well, we do want a core, even a very large core.  But we want the core to be written quickly, and any processing to be done after the supervisor (e.g. systemd) knows core processing is done and can restart the process.

**Comment by jfilak** [comment]
Yeah, abrt-hook-ccpp saves core file by copying bytes to user space because it might need to write them twice - to a core dump file in ABRT database and to a core dump file according to the old value of core_pattern. We should teach abrt-hook-ccpp to use more efficient way to do so when there is no need to write the old way core file.

**Comment by avikivity** [comment]
You could try writing it to core_pattern and analyzing it from there?

With pmem, or AWS X1, you can expect to see multi-terabyte cores soon.

**Comment by jfilak** [comment]
Is it necessary to save every bit of these core files or is there any chance we can find some optimization? We can probably ignore some parts of heap or maybe save only stack ...

**Comment by drbo** [comment]
Perhaps the solution is to dump the data to a temporary file first (possibly compressing it along the way), and then do all processing in a streaming fashion.

**Comment by jfilak** [comment]
ABRT save some meta-data [1] and writes the core dump to a file (not compressed because it will be decompressed few moments later). I believe writing core dump takes too much time because we read it by blocks in order to improve performance when saving sparse core dumps [2][3].

1: https://github.com/abrt/abrt/wiki/CCpp-plugin
2: https://github.com/abrt/abrt/blob/master/src/hooks/abrt-hook-ccpp.c#L44
3: https://bugzilla.redhat.com/show_bug.cgi?id=588945

**Comment by avikivity** [comment]
@jfilak in the general case you need all the core. Who knows where the bug might lurk?

**Comment by avikivity** [comment]
btw, when compressing, please use parallel compression (like `pigz`) or it will take very long.

**Comment by jfilak** [comment]
@avikivity Here is a short summary of what we have done so far:

Commit https://github.com/abrt/abrt/commit/bbf252621f834ad3d548acd72027b4fa35fec61b replaces the `read+write` functions with the `splice` function which does not need to copy data from kernel buffer to user space when saving core file. That will make saving cores a little bit faster, but there is no more room for further speed improvements in this area.

Core file processing is performed after the crashing process is restarted and ABRT core dumper prints out this message to system log:
`Process 21768 (will_segfault) of user 1000 killed by SIGSEGV - dumping core`

See commit https://github.com/abrt/abrt/commit/a72d05b10deb6303440f8a63c729d19d214ca964 for more details.

**Comment by xsuchy** [comment]
We are now (since F26) using coredumpctl. So the dump is created by systemd and we will analyze it later. Is this acceptable solution for you?

**Comment by xsuchy** [comment]
Closing per last comment.
