### ISSUE TITLE
ProcessUnpackaged not read from config file

### ISSUE THREAD

**Issue by zbigi-x86** [abrt/abrt#1150]
Hello,
I have unpackaged c++ application running on RHEL 6.8 (2.6.32-573.18.1.el6.x86_64) and following abrt packages installed:  
abrt-2.0.8-40.el6.x86_64
abrt-addon-ccpp-2.0.8-40.el6.x86_64

[xx@xx]# grep Unpackage /etc/abrt/abrt-action-save-package-data.conf
ProcessUnpackaged = yes

After restarting arbtd service it does not seem this change is taken into consideration.

abrt[43754]: Not saving repeating crash in 'my/bin'
abrt[43755]: Not saving repeating crash in 'my/bin'
abrtd: Executable 'my/bin' doesn't belong to any package and ProcessUnpackaged is set to 'no'
abrtd: 'post-create' on '/var/spool/abrt/ccpp-2016-06-03-16:03:36-43655' exited with 1
abrtd: Deleting problem directory '/var/spool/abrt/ccpp-2016-06-03-16:03:36-43655'

**Comment by xsuchy** [comment]
This work in upstream version (2.10.x). If there is a problem in the version included in RHEL, then please contact Red Hat Support. That is the best way how to get the fix into RHEL.

**Comment by jfilak** [comment]
Be sure that there are no white spaces after the value 'yes'. There is/was a bug in the abrt augeas lense.
