### ISSUE TITLE
Can translator translate ? 100% everywhere be still having english strings

### ISSUE THREAD

**Issue by Jibec** [abrt/abrt#1157]
Hi there, I am one of the translation team coordinator, and I noticed we still have untranslated strings in interface. I did the check with french language, but I assume it's global.

On zanata : 
- FR is 100% for ABRT project : https://fedora.zanata.org/project/view/abrt
- FR is 100% for ABRT-gnome project : https://fedora.zanata.org/project/view/gnome-abrt (btw, I still can't understand the difference)

On appdata (created by appstream-lib based on rpm in f24 repository), FR is also 100% : search abrt in https://alt.fedoraproject.org/pub/alt/screenshots/f24/fedora-24.xml.gz

But we still have many english strings :
![capture d ecran de 2016-06-30 12-42-14](https://cloud.githubusercontent.com/assets/474883/16485694/9cabde7e-3ec0-11e6-9ba8-36f9caa08170.png)
![capture du 2016-06-30 12-38-18-abrt](https://cloud.githubusercontent.com/assets/474883/16485696/9cafd966-3ec0-11e6-8230-030797841c31.png)
![capture du 2016-06-30 12-37-27-abrt](https://cloud.githubusercontent.com/assets/474883/16485695/9caf327c-3ec0-11e6-9620-8663b6c8fe1a.png)

Thanks for your help

**Comment by jfilak** [comment]
Hi, thank you for the report.

Some of those untranslated strings come from libreport  ("Search", "Sensitive words", "Custom").:
https://fedora.zanata.org/project/view/libreport
https://github.com/abrt/libreport/

Some of them ("Preparing environment ...") are produced by retrace-server  which is not tracked on zanata yet:
https://github.com/abrt/retrace-server

Some of them are probably unintentionally not marked for translation.

Finally some of them cannot be translated because of ABRT's design. For example the "The process had locked memory ..." is written to problem data in context of kernel (no locale available) and displayed as raw data in the GUI. We might be able to find a way how to translate such strings but it will not be easy.

**Comment by Jibec** [comment]
Thanks for your answer !

Libreport : we'll finish it, but I can't find .
Retrace-server : can you confirm po file are up to date ? 5 years without modification looks suspicious to me. I also created an request for zanata connexion so we don't forget it.

Can you please have a look for "unintentionally not marked for translation" strings ? I notice some strings are untranslated in git french po file, while 100% on Zanata. Maybe you should push your strings again on Zanata ?

**Comment by jfilak** [comment]
> Libreport : we'll finish it. But I noticed "Search" was translated on februrary 23/02/16 11:52 by Julie Carbone (RH employee).

Thank you for pointing this issue out. I updated libreport translations in the following commits:
https://github.com/abrt/libreport/commit/ed423e304c91ebb4afed729dd039140ed7754032

> Retrace-server : can you confirm po file are up to date ?

I regenerated retrace-server.pot and pushed it to zanata, so all po files should be up to date now.

> Can you please have a look for "unintentionally not marked for translation" strings ?

Thank you for pointing this issue out. I updated abrt translations in the following commits:
https://github.com/abrt/abrt/commit/b01f34a51ed2d2d9dc7168355014bd738d1f1d8b

Is there something else that needs to be addressed or can we close this issue now?

Your contribution is much appreciated. Thank you!

**Comment by Jibec** [comment]
sounds great !

> Is there something else that needs to be addressed or can we close this issue now?

yes, please give me the next expected release date?

I would like to tell the fedora translation community about what you just did and ask them to give some love to abrt, abrt-gnome, libreport and retrace-server translations. A deadline, even if it is in weeks or months would be great.

> Your contribution is much appreciated. Thank you!

Most of the time, we translate software we use or we like, please continue to help us helping you, if your stats goes down instead of improving, create a ticket to trans (rh bugzilla) or even better, send an email to trans@fedoraproject, we'll be please to help.

**Comment by piotrdrag** [comment]
> I regenerated retrace-server.pot and pushed it to zanata, so all po files should be up to date now.

It seems that in Zanata there is the same 5-year old .pot file that's in git, could you please double-check if everything's ok?

**Comment by jfilak** [comment]
> yes, please give me the next expected release date?

Unfortunately, we do not plan our releases. But I can assure you that you can ask us to do a release with updated translations when you find the translations good enough.

**Comment by jfilak** [comment]
> It seems that in Zanata there is the same 5-year old .pot file that's in git, could you please double-check if everything's ok?

I can confirm that everything is OK. We haven't added new strings for a quite long while :)

**Comment by Jibec** [comment]
I think everything is ok here, thanks for your help!
