### ISSUE TITLE
Update the Website link in the "About" window

### ISSUE THREAD

**Issue by mustafa1024m** [abrt/abrt#1159]
The link in the "About" window still refers the the old website, should be updated to the github project page.

**Comment by mkutlak** [comment]
This issue was fixed with commit 531f1ac5c401efe37e0107833bfbcac5fc0b5648

**Comment by mkutlak** [comment]
Correct URL https://github.com/abrt/gnome-abrt/commit/531f1ac5c401efe37e0107833bfbcac5fc0b5648
