### ISSUE TITLE
abrt-server: improve for loop in handle_signal_pipe_cb()

### ISSUE THREAD

**Issue by mhabrnal** [abrt/abrt#1167]
Inner for loop in function handle_signal_pipe_cb() goes always only once even if there are more then one signal red.

```
for (unsigned signo = 0; signo < len; ++signo)
        {
            /* we did receive a signal */
            struct waiting_context *context = (struct waiting_context *)user_data;
            log_debug("Got signal %d through signal pipe", signals[signo]);
            switch (signals[signo])
            {
                case SIGUSR1: context->reply = ABRT_CONTINUE; break;
                case SIGINT:  context->reply = ABRT_INTERRUPT; break;
                default:
                {
                    error_msg("Bug - aborting - unsupported signal: %d", signals[signo]);
                    abort();
                }
            }

            g_main_loop_quit(context->main_loop);
            return FALSE; /* remove this event */
        }
    }

    return TRUE; /* "please don't remove this event" */
```

The for loop ends either with return FALSE in case the required signal is received or it is aborted. The others received signals are not processed. abrt-server should get only one signal so the for loop should work here like some bug checker and write error messages in case more then one signal is received.

**Comment by ernestask** [comment]
571f0d02a53de785bd747d36f4b1a42b3a40c618 went in a different direction. Only one signal is read at all times.
