### ISSUE TITLE
save /proc/cpuinfo in problem directories

### ISSUE THREAD

**Issue by jfilak** [abrt/abrt#1171]
Crashes in some components (e.g. nss-softokn) are related to HW acceleration. The file must be captured for all crashes because of the library vs. executable problem.

**Comment by nmav** [comment]
+1
I have a crash with SIGILL which is related to HW acceleration in gmp and ABRT's information are not sufficient to reproduce or understand the issue.

https://bugzilla.redhat.com/show_bug.cgi?id=1350685

**Comment by juliusmilan** [comment]
What is needed to do after saving /proc/cpuinfo?
Is it needed to fill its data into ureport or somewhere else?

**Comment by jfilak** [comment]
It should be enough to have the information attached to Bugzilla bugs. I am not an expert in this matter but `flags` might be of some use in FAF - especially if we provide users with the functionality to analysis this information. I think `cpuinfo` and possibility to use this information in FAF filtering/querying can be appreciated also by Kernel developers. Ask Anton Arapov - or better send an email to Fedora kernel mailing and RHEL too - they will tell you if they need it. Tools team - those cool hackers developing compilers - might want to see it in FAF too. Do we have crashes of compilers in FAF?

**Comment by jfilak** [comment]
But first of all, just add a new `EVENT=post-create` saving the file in problem directories. Then generate all problem for all types, check how problem data looks on command line and in gnome-abrt, report the problems to partner-bugzilla and check if the reports contains the file. Introducing a new problem element might have unforeseen consequences. 

Be prepared, that some developers will complain about another useless attachment in Bugzilla.
