### ISSUE TITLE
Add new ignored privacy keywords

### ISSUE THREAD

**Issue by kparal** [abrt/abrt#1180]
![abrt](https://cloud.githubusercontent.com/assets/755451/18342903/507543e2-75b1-11e6-8edf-93c7ade938b1.png)

abrt-2.8.2-2.fc25.x86_64

**Comment by kparal** [comment]
Also please add `hawkey`.
![snimek z 2016-09-14 10-04-24](https://cloud.githubusercontent.com/assets/755451/18504457/aafb8c58-7a62-11e6-99d0-60c1f8973372.png)

**Comment by mhabrnal** [comment]
Closed by commit https://github.com/abrt/libreport/commit/cec2e658aa7b98987cc2b8140cc351e6bc1b9b90
