### ISSUE TITLE
Abrt Error abrt-cli list --since 1484935231

### ISSUE THREAD

**Issue by Zulqarnainkhan** [abrt/abrt#1220]
Hi, hopping everyone is fine. I am using a Centos 7 server based on Nginx.
I am using the server for providing downloadable data. Around 8 TB per day is downloaded. The server was working fine and perfectly. 

I hired a freelancer to limit the download speed as i am unexperienced with linux (Worst Mistake Ever)

he messed up the server and after 4 hours said he cant impletement a simple limit_rate in Nginx. So i said to him revert back the changes and he said its done.

Since then i am getting this error **abrt-cli list --since 1484935231** 

Error typed in terminal http://prntscr.com/dy6c4a

Here is the Nginx log file http://prntscr.com/dy6k54

Here is my Php-fpm log file http://prntscr.com/dy6koa

There servers is taking too much time to respond. Even a simple yum is taking time to respond. Listing directories is also taking time.

So please help me out.

**Comment by jfilak** [comment]
I'm not sure we can help you here. ABRT is just a messanger which brings problems to user's attention.

I belive that the CentOS mailing list is the best place to ask for help on your matter:
https://lists.centos.org/mailman/listinfo/centos

The only advice we can give you here is to use ABRT to report the PHP crash to CentOS maintainers. Just issue this command:
```abrt-cli report /var/spool/abrt/ccpp-2017-01-17-16:07:53-2320```

Perhaps someone else has already reported the same issue and CentOS maintainers have fixed it. ABRT should give you this information after the reporting process finishes.

I hope you will heal your server. Fingers crossed!

**Comment by Zulqarnainkhan** [comment]
OK thanks alot for the reply.
