### ISSUE TITLE
Blacklist for users

### ISSUE THREAD

**Issue by paulraines68** [abrt/abrt#1226]
Is there currently a way to make abrt totally ignore crashes of programs running under specific user ids?  I don't mean just prevent notifications, but not even create dumps in /var/tmp/abrt in the first place?  I would like to ignore all crashes by programs running with UID > 100

If there is not, then as a feature request there should be a way to Blacklist via the user id running the crashing program, preferably via uid range so something like

BlacklistUser = 100-

would mean all user ids over 100

**Comment by xsuchy** [comment]
This can be done with our current code. It is just matter of writing proper config.
We will try to document this.

**Comment by mzidek-gh** [comment]
> This can be done with our current code. It is just matter of writing proper config.
> We will try to document this.

Hi,

I have found a support for blacklisting packages, but not UIDs. So I think this is indeed an RFE not just a documentation change. But maybe I am  not looking at the right places in code.

**Comment by xsuchy** [comment]
I believe this can be achieved using `/etc/libreport/events.d/*`. You may check `events.d/ccpp_event.conf` which has at the beginning example that not ptraced crashes exit with 1 and the problem directory is not created then. So you need to create post-trace even which check for $uid and when bigger than 100 (1000 is actually a better number for the example) then you exit with 1 and therefore not create the problem directory.

**Comment by mzidek-gh** [comment]
You are correct, doing
```
grep '^Uid:[[:space:]]*' proc_pid_status`` returns the UID line and it is possible to work with it.
```
in ```EVENT=post-create``

returns the UID line and it is possible to use it as you mentioned. I will add an example snippet somewhere in the documentation.
