### ISSUE TITLE
abrtd constantly consumes cpu

### ISSUE THREAD

**Issue by timgesekus** [abrt/abrt#1230]
Abrtd constantly consumes cpu. I'm not able to reproduce it, but it keeps happening randomly.

strace output of the process is:

```
poll([{fd=3, events=POLLIN|POLLPRI}, {fd=5, events=POLLIN}, {fd=6, events=POLLIN|POLLPRI}, {fd=9, events=POLLIN|POLLPRI}, {fd=17, events=POLLIN}], 5, -1) = 1 ([{fd=17, revents=POLLNVAL}])
poll([{fd=3, events=POLLIN|POLLPRI}, {fd=5, events=POLLIN}, {fd=6, events=POLLIN|POLLPRI}, 

```
over and over again.

ps faxl
```
4     0  1394     1  20   0 447212 10280 -      Rsl  ?         93:05 /usr/sbin/abrtd -d -s
0     0  3550  1394  20   0 225864  8668 -      S    ?          0:00  \_ abrt-server -s

```
Host is fedora 25
abrt-2.9.0-1.fc25.x86_64

This is a very annoying for a laptop, as it drains the battery really fast.

**Comment by xsuchy** [comment]
I am not sure if we can do anything about it without reproducer. :(

**Comment by xsuchy** [comment]
resolved by https://github.com/abrt/abrt/pull/1321
