### ISSUE TITLE
Error: scylla-server conflicts with abrt-2.1.11-45.el7.centos.x86_64

### ISSUE THREAD

**Issue by nwbrad** [abrt/abrt#1249]
Trying to install Package scylla.x86_64 0:1.7.0-0.20170519.25607ab.el7.centos
through the normal install process: yum install scylla
release: CentOS Linux release 7.3.1611 (Core)
yum update is current as of today (05/26/2017)

yum install scylla aborts with:
--> Finished Dependency Resolution
Error: scylla-server conflicts with abrt-2.1.11-45.el7.centos.x86_64

**Comment by nwbrad** [comment]
Sorry, should have been reported under scylla.

**Comment by jfilak** [comment]
Anyways, the conflict is intentional. Scylla generates huge core dump files and they don't want to run scylla if ABRT is in place. See the issue https://github.com/scylladb/scylla/issues/892 for more details.
