### ISSUE TITLE
Do not report user code into FAF and BZ

### ISSUE THREAD

**Issue by marusak** [abrt/abrt#1256]
When I write some of my own code and it crashes ABRT catches it. Since it is enabled by default in /etc/abrt/abrt-action-save-package-data.conf (ProcessUnpackaged = yes).
That is fine and sometimes even useful (I read some discussion on this whether it should be enabled or not) but my concern is that it also enables reporting it into FAF (and BZ as well). The reporting usually crashes since it cannot get packages information.
I think we should not enable reporting into FAF (at least not by default).

**Comment by jfilak** [comment]
Sure. There are two ways how to achive that goal - either turn off the event report_uReport (add package!=) or introduce a new configuration option for the tool abrt-action-ureport.

**Comment by xsuchy** [comment]
The default is now ProcessUnpackaged = no
