### ISSUE TITLE
Unable to install to prefix without make install doing operations in the default install path.

### ISSUE THREAD

**Issue by Yetoo1** [abrt/abrt#1288]
In the current master branch, after executing `./autogen.sh --prefix=$PWD/a` and issuing `make`, `make install` attempts to do operations under the root protected machine directories (/bin, /etc, etc...), or the default install path. The log file can be found here: [b.txt](https://github.com/abrt/abrt/files/1692116/b.txt)
I also get a similar result when I execute `./autogen.sh --prefix=$PWD/a/usr --sysconfdir=$PWD/a/etc --localstatedir=$PWD/a/var --sharedstatedir=$PWD/a/var/lib`

**Comment by xsuchy** [comment]
It should work with --destdir. But we do not support working with some other prefix. If you need this we will gladly accept and review PR. Just do not expect that anyone from core team will work on this anytime in the future.

**Comment by ernestask** [comment]
https://www.gnu.org/prep/standards/html_node/DESTDIR.html

I imagine we might only have hardcoded some paths.
