### ISSUE TITLE
Actualize man pages

### ISSUE THREAD

**Issue by xsuchy** [abrt/abrt#1299]
Description of problem:
There are some man pages which are not up to date.

* abrt-action-install-debuginfo - "--repo" parameter is not documented in the man page (see "$ man abrt-action-install-debuginfo" and "$ abrt-action-install-debuginfo --help")

* abrt-handle-upload - there are no parameters documented in the man page (see "$ abrt-handle-upload" and "$ abrt-handle-upload --help)

* report_Bugzilla.conf and reporter-bugzilla - there are undocumented parameters "Bugzilla_CreatePrivate" and Bugzilla_PrivateGroups in those man pages

**Comment by mgrabovsky** [comment]
It seems the last point has been fixed already. Both parameters are documented in the man pages.
