### ISSUE TITLE
request: automatically clear events from known processes

### ISSUE THREAD

**Issue by darthyoshi** [abrt/abrt#1320]
I looked through the existing issues and didn't see anything like this, so here goes. Basically, every time I turn off my bluetooth adapter (whether it's because I'm shutting down the computer or simply because I don't need bluetooth for the moment), a whole bunch of SIGABRT events get logged, and sometimes a bunch of desktop notifications pop up all at once as well. This also happens with some games if I quit using ALT+F4 instead of going through the menu to quit. As these aren't actually bugs that need reporting, I'd like the option to automatically clear certain kinds of events from certain processes.

**Comment by marusak** [comment]
> ... a whole bunch of SIGABRT events get logged ...

This is definitely not how a program should end up. Maybe file issue against bt adapter.

> I'd like the option to automatically clear certain kinds of events from certain processes.

You can do it now. In `/etc/abrt/abrt-action-save-package-data.conf` you can blacklist both packages or event specific paths. Does it provides what you have been asking for, or you need something more specific?

**Comment by marusak** [comment]
How do you define event?

**Comment by darthyoshi** [comment]
In my specific case, I mean whenever abrt logs that bt-adapter got killed by SIGABRT. Basically, I want it so that instead of logging an application crash and displaying a desktop notification, abrt detects that the crashed binary was "bt-adapter" and the reason was "bt-adapter was killed by SIGABRT" or however I'd be identifying the entry, and automatically deletes it from the log without my input.

**Comment by jfilak** [comment]
Did you try to put "bt-adapter" into the configuration file `/etc/abrt/abrt-action-save-package-data.conf` as suggest by @marusak ? Because abrt should not log anything and it should not even create any entry, if a crash comes from a blacklisted binary.

**Comment by darthyoshi** [comment]
Yes, I did try, and it seems to be working. So I guess I'll close this issue...
