### ISSUE TITLE
Comparison of unsigned values has no effect

### ISSUE THREAD

**Issue by mkutlak** [abrt/abrt#1345]
In the GNU C Library, `uid_t` is an alias for `unsigned int`. See [Reading the Persona of a Process](https://www.gnu.org/software/libc/manual/html_node/Reading-Persona.html)

https://github.com/abrt/abrt/blob/3422a79ff8dcb6ae5a16198c6d2c3723c5e157f2/src/plugins/abrt-dump-journal-core.c#L244
This less-than-zero comparison of an unsigned value is never true. "tmp_fsuid < 0U". 

https://github.com/abrt/abrt/blob/3422a79ff8dcb6ae5a16198c6d2c3723c5e157f2/src/dbus/abrt_problems2_service.c#L693
This greater-than-or-equal-to-zero comparison of an unsigned value is always true. "owner_uid >= 0U".

**Comment by webera** [comment]
Hi! Just came across this repo and had a short look at the issue.

I think the second referenced line has one more depth - the uid is retrived using `dd_get_owner`

https://github.com/abrt/abrt/blob/a2a2516d77291e76063eae5e07c4c44428b7b2cb/src/dbus/abrt_problems2_entry.c#L972

Whereas `dd_get_owner` from libreport itself returns type `uid_t` but (in case of an error of the called function `read_number_from_file_at`) wants to return a negative value which is then messed up and not checked by the caller of dd_get_owner

https://github.com/abrt/libreport/blob/5e0c2c3839f7205a90aedd6be7a1f54bc4306ebb/src/lib/dump_dir.c#L753
https://github.com/abrt/libreport/blob/5e0c2c3839f7205a90aedd6be7a1f54bc4306ebb/src/lib/dump_dir.c#L759
https://github.com/abrt/libreport/blob/5e0c2c3839f7205a90aedd6be7a1f54bc4306ebb/src/lib/dump_dir.c#L216

So I guess there is also a change in libreport required to fix this right?

**Comment by mgrabovsky** [comment]
Should be fixed now by #1484 and abrt/libreport#630.
