### ISSUE TITLE
Please blacklist packages

### ISSUE THREAD

**Issue by leigh123linux** [abrt/abrt#1346]
Please add

cinnamon
cinnamon-settings-daemon
cinnamon-screensaver
cinnamon-desktop
cinnamon-session
nemo
muffin

**Comment by xsuchy** [comment]
Can you please elaborate on the reasoning?

**Comment by leigh123linux** [comment]
Each report generates many separate emails, I can't handle this amount of spam.

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/4XMEL2YXLIHVBYL5HW2YZOGYG2LOKJP3/
