### ISSUE TITLE
“uReport data is invalid” on gnome-shell crash triggered by Android file sharing connection

### ISSUE THREAD

**Issue by rugk** [abrt/abrt#1368]
I have a gnome-shell crash reported at https://gitlab.gnome.org/GNOME/gnome-shell/issues/999 that abrt was unable to process. As explained there I get a log as this:
> This crash could not be uploaded. Server says uReport data is invalid.

…and link: https://retrace.fedoraproject.org/faf/dumpdirs/new/ccpp-2019-02-26-21:48:45.566013-18208.tar.gz

I am not sure whether it is something you can do about, but I guess at least uReport data should always be valid, should not it? (It could not even upload these…)

So I opened the report here, too.

**Comment by ernestask** [comment]
@rugk, do you still have the problem directory around?

**Comment by rugk** [comment]
This is one year ago! So no… Also [the GNOME bug report has been closed](https://gitlab.gnome.org/GNOME/gnome-shell/issues/999), so I guess this is fixed?

**Comment by ernestask** [comment]
Still worth a shot. I wouldn’t ask if I could access it and, in the near future, it will be impossible altogether. I had fixed one instance of this recently (though I forget the context now), but, for future reference, it would be useful to have the generated micro-report (which you can see by running `reporter-ureport` directly with a sufficient number of `-v` arguments).

**Comment by ernestask** [comment]
Closing for now.
