### ISSUE TITLE
abrt-console-notification.sh error if noclobber is set: abrt/lastnotification.<TMP_SUFFIX>: cannot overwrite existing file

### ISSUE THREAD

**Issue by ScottABrown** [abrt/abrt#1371]
This in abrt/src/cli/abrt-console-notification.sh:

        date +%s > "$TMPPATH" 2>"$ABRT_DEBUG_LOG"

fails if noclobber has been set. If $TMPPATH points to a file to be replaced, it should be removed explicitly first.

**Comment by jfilak** [comment]
D'oh, did it print out the error message to your terminal? (I tried so hard to mute all errors).

The command should create a file holding the date of the last notification. The script tries to robust, so it first creates a temporary file and if it succeeds, it adds the content.

The failing command can be replaced with `date +%s >>" to get rid of the failure - I hope there is no option preventing commands from appending files :)

The redirects should be swapped to avoid errors being printed out - i.e. first  `2>"$ABRT_DEBUG_LOG" > "$TMPPATH"` - the goal was quietly fail even if this is a valid bug.

**Comment by xsuchy** [comment]
Note for myself - what is noclobber:
https://www.linuxhowtos.org/Tips%20and%20Tricks/Protecting%20files%20with%20noclobber.htm
