### ISSUE TITLE
abrt-cli: behaviour of list and remove commands not consistent with documentation

### ISSUE THREAD

**Issue by michalfabik** [abrt/abrt#1374]
`$ abrt-cli list [-d] <ID_OR_PATH>` ignores the last argument and always lists all crashes, which is not consistent with https://abrt.readthedocs.io/en/latest/usage.html. The description therein fits what `abrt-cli info` does.  
  
`$ abrt-cli remove <ID_OR_PATH>` only accepts directory as argument and not crash ID.

**Comment by ernestask** [comment]
Obsoleted by https://github.com/abrt/abrt/commit/bd0315b9b24c644b388abe4ae4b8ae2cdaec585b.
