### ISSUE TITLE
Lacks bulk delete / remove all / remove all

### ISSUE THREAD

**Issue by ringerc** [abrt/abrt#1389]
Both abrt-cli and the GUI lack an obvious bulk-delete or "delete all" option (2.12.0).

That's not super fun when you have a vast number of reports from a kernel oops spamming 10x per second.

I used the GUI and held down the delete key. That worked. An awk script to process the results of `abrt-cli ls` should do the job too.

It looks like the `abrt-cli-ng` tool `abrt` supports `abrt rm '*'` but making this more obvious wouldn't hurt, especially as it doesn't seem to be installed by default (F29).

**Comment by ringerc** [comment]
Correction, `abrt rm '*'` doesn't work.

The docs say

>        MATCH can be either component name, short hash (from list subcommand) or combination of both in form <component>@<hash>

but it looks like it doesn't handle wildcards.

So I landed up writing this incantation to work around it:

    abrt-cli ls | awk '/^Directory:/ { print $2; }' | sudo xargs abrt-cli rm

The new cli appears not to accept multiple arguments to `rm` unlike the old one, which is unfortunate. So while slower, you can use

    sudo abrt ls | awk '/^Id/ { print $2; }' | xargs -n 1 abrt rm

with it.

**Comment by ernestask** [comment]
Resolved with https://github.com/abrt/abrt/pull/1415.

**Comment by ernestask** [comment]
Oh, nevermind, that wasn’t merged.
