### ISSUE TITLE
[RFC] Consolidate abrt-cli and abrt-cli-ng

### ISSUE THREAD

**Issue by ernestask** [abrt/abrt#1394]
We have two CLI tools for working with problems and both achieve pretty much identical goals, so it might be a good idea to finally drop one of them or combine the good parts of both into a third one.

## Maintainability

`abrt-cli-ng` was written in Python, which, IMO, is going in the right direction as opposed to choosing C. This is a rather uncomplicated tool, but `abrt-cli` even reinvents command-line parsing. On the other hand, `abrt-cli` has better code organization.

## Compatibility

- The console notification script depends on `abrt-cli`, which would call for a port/rewrite.
- `abrt-cli-ng` retains the long forms of the commands/optional arguments, inherited from `abrt-cli` with the exception of `--authenticate`, which became `--auth`.
- `abrt-cli-ng` seems to ship something that looks like an attempt at a bash completion script.
- Both seem to communicate with ABRT over D-Bus for the most part.
- `abrt-cli` allows processing multiple problems interactively

### Related RFEs

https://github.com/abrt/abrt/issues/290
https://github.com/abrt/abrt/issues/291
https://github.com/abrt/abrt/issues/292
https://github.com/abrt/abrt/issues/293
https://github.com/abrt/abrt/issues/631
https://github.com/abrt/abrt/issues/841
https://github.com/abrt/abrt/issues/934
https://github.com/abrt/abrt/issues/1028
https://github.com/abrt/abrt/issues/1279
https://github.com/abrt/abrt/issues/1374
https://github.com/abrt/abrt/issues/1389

### Related BZ bugs

https://bugzilla.redhat.com/show_bug.cgi?id=1329711
https://bugzilla.redhat.com/show_bug.cgi?id=1329712

**Comment by ernestask** [comment]
One idea I had was to make the command-line tool available with the main package and make it properly pluggable with `abrt-action-*` binaries turned into plugins for it (not unlike FAF). That would also help despaghettify the code for some of them.

**Comment by cmurf** [comment]
Top complaints.

1. The trailing / causes an error
[root@flap ~]# abrt-cli report /var/spool/abrt/ccpp-2019-06-19-16\:40\:16.735919-30984/
Can't test whether the element exists over abrt-dbus: GDBus.Error:org.freedesktop.problems.InvalidProblemDir: '/var/spool/abrt/ccpp-2019-06-19-16:40:16.735919-30984/' is not a valid problem directory
Problem '/var/spool/abrt/ccpp-2019-06-19-16:40:16.735919-30984/' cannot be reported
[root@flap ~]# 

2. Of course if I'm not root and use sudo, I don't get a trailing / by default because I can't do tab to complete, as apparently an admin user doesn't have permission to list the contents of abrt/

3. Problem reports don't consistently contain either a complete journal or dmesg. If there's a kernel warning or opps that triggers abrt, then dmesg is included, but often with user space problems, dmesg isn't included.

**Comment by cmurf** [comment]
Really, these are more important and more annoying recent experiences.


1. When abrt says a crash has low informational value and won't report it. When I can spend three hours downloading a bagillion debuginfos, and only then abrt tells me there's a dup, and yet the retrace server can't do that for me? Something's not working correctly. But this happens a lot and everytime it makes me irrationally annoyed.
My bug report
https://bugzilla.redhat.com/show_bug.cgi?id=1723242
The apparent dup
https://bugzilla.redhat.com/show_bug.cgi?id=1697566
And the faf URL, so local abrt knows this is a dup at some level, it just doesn't actually tell me until I've spent hours troubleshooting i
https://retrace.fedoraproject.org/faf/reports/2601736/

2. Support flatpak crash reporting: i.e. how to install all the debuginfos for runtimes and apps, how to run flatpak-coredumpctl, how to extract all that info so I don't have to witness the sausage making, etc.

**Comment by ernestask** [comment]
> Really, these are more important and more annoying recent experiences.
> 
>     1. When abrt says a crash has low informational value and won't report it. When I can spend three hours downloading a bagillion debuginfos, and only then abrt tells me there's a dup, and yet the retrace server can't do that for me? Something's not working correctly. But this happens a lot and everytime it makes me irrationally annoyed.
>        My bug report
>        https://bugzilla.redhat.com/show_bug.cgi?id=1723242
>        The apparent dup
>        https://bugzilla.redhat.com/show_bug.cgi?id=1697566
>        And the faf URL, so local abrt knows this is a dup at some level, it just doesn't actually tell me until I've spent hours troubleshooting i
>        https://retrace.fedoraproject.org/faf/reports/2601736/
> 
>     2. Support flatpak crash reporting: i.e. how to install all the debuginfos for runtimes and apps, how to run flatpak-coredumpctl, how to extract all that info so I don't have to witness the sausage making, etc.

These are going out of scope.

**Comment by ernestask** [comment]
> * The trailing / causes an error
>   [root@flap ~]# abrt-cli report /var/spool/abrt/ccpp-2019-06-19-16:40:16.735919-30984/
>   Can't test whether the element exists over abrt-dbus: GDBus.Error:org.freedesktop.problems.InvalidProblemDir: '/var/spool/abrt/ccpp-2019-06-19-16:40:16.735919-30984/' is not a valid problem directory
>   Problem '/var/spool/abrt/ccpp-2019-06-19-16:40:16.735919-30984/' cannot be reported
>   [root@flap ~]#

Sure, this has already been reported several times. Fix is rather trivial.

> * Problem reports don't consistently contain either a complete journal or dmesg. If there's a kernel warning or opps that triggers abrt, then dmesg is included, but often with user space problems, dmesg isn't included.

Also out of scope.

**Comment by ernestask** [comment]
abrt-cli-ng has replaced abrt-cli. Other requested fixes will follow in the next release.
