### ISSUE TITLE
abrt-hook-ccpp high RES memory

### ISSUE THREAD

**Issue by motherfxxk** [abrt/abrt#1395]
hi
![image](https://user-images.githubusercontent.com/41286056/59591243-44c12380-9120-11e9-8d55-2ee8421cc3a2.png)

look like the process abrt-hook-ccpp are running  more then 22hours,and take more than 100G RES memory. do not know the reason,so i check the messages log

```
> `Jun 11 11:31:59 localhost abrt-hook-ccpp: Process 361013 (vim) of user 500 killed by SIGSEGV - dumping core`
Jun 12 09:23:42 localhost abrt-hook-ccpp: Failed to create core_backtrace: dwfl_linux_proc_report failed: no error
Jun 12 09:31:09 localhost abrt-hook-ccpp: Process 3245 (beaver_master) of user 500 killed by SIGABRT - dumping core
Jun 12 09:31:11 localhost abrt-hook-ccpp: Failed to create core_backtrace: waitpid failed: No child processes
Jun 12 10:00:58 localhost abrtd: Size of '/var/spool/abrt' >= 1000 MB (MaxCrashReportsSize), deleting old directory 'ccpp-2019-06-11-11:31:59-361013.new'
Jun 12 10:00:58 localhost abrtd: Size of '/var/spool/abrt' >= 1000 MB (MaxCrashReportsSize), deleting old directory 'ccpp-2019-06-12-09:31:09-3245'
Jun 12 10:00:58 localhost abrt-hook-ccpp: /var/spool/abrt is 23379248478 bytes (more than 1279MiB), deleting 'ccpp-2019-06-12-09:23:15-433'
Jun 12 10:00:58 localhost abrt-server: Path '/var/spool/abrt/ccpp-2019-06-12-09:31:09-3245' isn't directory
Jun 12 10:00:58 localhost abrt-server: Problem directory '/var/spool/abrt/ccpp-2019-06-12-09:31:09-3245' isn't owned by root:abrt or others are not restricted from access
Jun 12 10:00:58 localhost abrt-server: Lock file '.lock' is locked by process 3357
Jun 12 10:00:58 localhost abrt-server: '/var/spool/abrt/ccpp-2019-06-12-09:23:15-433' does not exist
Jun 12 10:00:58 localhost abrt-server: 'post-create' on '/var/spool/abrt/ccpp-2019-06-12-09:23:15-433' exited with 1
Jun 12 10:00:58 localhost abrt-server: Deleting problem directory '/var/spool/abrt/ccpp-2019-06-12-09:23:15-433'
Jun 12 10:00:58 localhost abrt-server: '/var/spool/abrt/ccpp-2019-06-12-09:23:15-433' does not exist
Jun 12 10:01:14 localhost abrtd: Got signal 15, exiting
Jun 12 10:01:14 localhost abrtd: Init complete, entering main loop
```

thanks!can you explain the reason!thanks a lot~

**Comment by mkutlak** [comment]
What is the version of `abrt`?

**Comment by motherfxxk** [comment]
it is abrt 2.1.11

**Comment by motherfxxk** [comment]
it must somthing wrong with abrt？ the abrt-hook-ccpp take 100GRES  but i can not reproduce the problem？@mkutlak

**Comment by ernestask** [comment]
The version you are running is rather ancient, and I can only assume you’re running CentOS. As an upstream, we’re only interested in issues that are present in current code, so your report should go downstream.

Other than that, this report is not actionable. If we knew the reason for this, it wouldn’t be happening.

**Comment by mkutlak** [comment]
The problem was fixed in https://github.com/abrt/abrt/commit/d965a43042b11eaed00ca49fcb060592082c398c . And release to Fedora with `abrt-2.11.0-1.fc29` 

> it is abrt 2.1.11

I guess you are running a CentOS, in that case it should be fixed in a future release of `abrt`.

For now the options are to kill the `abrt-hook-ccpp` process or restart the `abrtd` process.

```
$ systemctl restart abrtd
```

Sorry for the trouble.
