### ISSUE TITLE
Possible sensitive data detected is always a false positive

### ISSUE THREAD

**Issue by mcatanzaro** [abrt/abrt#1399]
Almost every backtrace processed by ABRT is flagged as having possible sensitive data detected because of stupid keyword matching. E.g. anytime a hash table appears in a backtrace, it's considered sensitive because hash tables have keys:

![Screenshot from 2019-07-02 11-15-51](https://user-images.githubusercontent.com/1424966/60528834-f59bf680-9cba-11e9-9ec7-3cc03bc3c730.png)

(Hash tables appear in a huge amount of backtraces.)

Or here in the open_fds, the application has ~~/etc/passwd~~ a passwd file open. There's nothing sensitive about this because the contents of the file do not get copied into the ABRT report and the odds of the backtrace including anything sensitive just because a file is open are astronomically small:

![Screenshot from 2019-07-02 11-16-02](https://user-images.githubusercontent.com/1424966/60528967-2da33980-9cbb-11e9-9673-0d352f8ee55d.png)

Since this feature almost never detects anything actually sensitive, it's negative-value IMO. In my experience working with user-uploaded backtraces over the past six years, sensitive data takes two forms:

 * http:// or https:// URLs revealing that the user was visiting an embarrassing website. I don't remember if URLs actually get flagged by ABRT (they probably should).
 * (Very rare) actual passwords actually flagged by ABRT's check for "pass," which the user missed because **users have been trained to ignore everything ABRT flags as false positives**. I've seen this once or twice. Recently I had to warn a user that his password was uploaded to Bugzilla, which probably could have been prevented if ABRT warned only rarely; then users might take the warnings seriously.

It's also harmful because almost every backtrace uploaded to Red Hat Bugzilla gets set to private, since that's the default whenever ABRT detects possible sensitive data. This dramatically  reduces the number of developers able to help fix the bug, and also results in ABRT filing a bunch of duplicate bugs for the same problem.

So there are two ways to solve this:

 * Either just remove the feature outright, or
 * Dramatically reduce the number of keywords to search for. Never warn about "key," unless perhaps it's "privatekey" or some variant of that. Never warn about "pass" unless it appears in the backtrace itself, not the open_fds. There are probably more oversensitive keywords, but these are the two that I see in front of me right now.

**Comment by mcatanzaro** [comment]
Now it's flagging /proc/cpuinfo:

![Screenshot from 2019-09-18 08-54-01](https://user-images.githubusercontent.com/1424966/65154914-f3138800-d9f1-11e9-9277-bcc88040e4f8.png)

Please, just *disable this feature entirely* if you don't have time to improve it now.

**Comment by mcatanzaro** [comment]
Also, folks backends:

![Screenshot from 2019-09-18 08-55-09](https://user-images.githubusercontent.com/1424966/65154975-0d4d6600-d9f2-11e9-9a5b-11ec483ae94d.png)

**Comment by mcatanzaro** [comment]
> Please, just _disable this feature entirely_ if you don't have time to improve it now.

Hey, ABRT devs. I know you're probably very busy... but if you don't have time to address issues like this, Fedora will have to consider dropping the GUI from the default install and keeping automatic reports to FAF only. Our quality requirements are simply higher than this.

**Comment by ernestask** [comment]
Well, one does not simply remove the GUI bits, because they’re hidden within libreport. I’m looking into moving them over to gnome-abrt and I can look into this if that works out well.

**Comment by ernestask** [comment]
Or maybe it is just one package, I don’t actually recall. Still, that’s my plan for this.

**Comment by mcatanzaro** [comment]
See also: https://github.com/abrt/libreport/issues/311

**Comment by mcatanzaro** [comment]
OK, here the most embarrassing issue -- flagging every bug report as sensitive due to the word "bypass" in /proc/cpuinfo -- was already fixed in 996afbc38413af2e2329efa360511c64aff76ee7. So that's a good start.

The trickiest problem is hash tables. Originally I was thinking we should try ignoring any lines that contain "key" if the line also contains the string "hash", but this fails for the case in the very first screenshot in this issue (g_settings_real_change_event()). e could significantly reduce false positives by accounting for the case where the key is a pointer value. I think we can simply add "key=0x" and "keys=0x" to the allowlist. That should cover GHashTable, most glib-style hash maps, and the first failure screenshot in this issue, and the chances of false negatives should be very low because the pointer value itself should not be sensitive, and the odds of this pattern being matched by actual sensitive data should be low. It will not help with C++, though. That's going to be harder. I figure we can tackle such problems in the future as they are discovered in actual backtraces.

That leaves "key-file" and "passwd". I would add "key-file" to the allowlist, for sure. As for "passwd"... it's *probably* also OK to allow, but it would be even better to just not check open_fds or maps for sensitive data. Yes, it's theoretically possible that sensitive data might be contained in a filename, but the odds of a false positive are way higher.

> (Very rare) actual passwords actually flagged by ABRT's check for "pass," which the user missed because users have been trained to ignore everything ABRT flags as false positives. I've seen this once or twice. Recently I had to warn a user that his password was uploaded to Bugzilla, which probably could have been prevented if ABRT warned only rarely; then users might take the warnings seriously.

If we can tackle these common cases now, then we can continually improve the allowlist as more false positives are detected in the future. I fear current users have likely been permanently trained to ignore ABRT when it flags sensitive data, but there is still hope for future users.

**Comment by xsuchy** [comment]
* do not report key=0x
* do not report sensitive word if it seems to be part of file path.
* do not report anything in cpuinfo at all. Meybe even open_fds and maps tab.

**Comment by mcatanzaro** [comment]
> * do not report key=0x

Or keys=0x

**Comment by mgrabovsky** [comment]
Fixed in #709.
