### ISSUE TITLE
need hires app icon

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#140]
Opened '20110315T22:45:30' by mccann as https://fedorahosted.org/abrt/ticket/148

The Abrt icon appears blurry in GNOME 3 because GNOME displays high resolution images by default and Abrt only provides a 48px app icon.  We should try to install a 256px icon as well.

**Comment by hadess** [comment]
abrt-applet doesn't install its own icon anymore, it uses gnome-abrt's. gnome-abrt ships icons up to 256x256 in bitmap, and a scalable SVG icon.
