### ISSUE TITLE
Wording of unreportable kernel-core errors

### ISSUE THREAD

**Issue by ferdnyc** [abrt/abrt#1410]
> The backtrace does not contain enough meaningful function frames to be reported. It is annoying but it does not necessary signalize a problem with your computer. ABRT will not allow you to create a report in a bug tracking system but you can contact kernel maintainers via e-mail.

"Signalize" is not a real word.

**Comment by ferdnyc** [comment]
Alright, I stand correctinated. (Though I'll note the usage in this sense  is marked "nonstandard" @ wiktionary.)

**Comment by ernestask** [comment]
If you feel like it could be worded better, please create a pull request. Otherwise, I have a feeling the issue would rot.
