### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [abrt/abrt#1427]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by ernestask** [comment]
Thanks for the bombshell. I’m pretty sure we’ll need to read about how Weblate works altogether before being able to answer your questions.

**Comment by Jibec** [comment]
We can iterate and test together, no worries. Do not hesitate to ask questions.

**Comment by marusak** [comment]
@ernestask I did this move in Cockpit projects (2 out of 3 for now). I tried a few wrong paths before we found somewhat reasonable solution. So if you want to ask something, feel free to stop by my desk :)

**Comment by ernestask** [comment]
Project on Zanata locked, but otherwise things are the same as here: https://github.com/abrt/retrace-server/issues/283#issuecomment-572047887

**Comment by Jibec** [comment]
could you please:

- remove empty po files (use file size or "pocount" from "translation toolkit")
- commit pot file

**Comment by ernestask** [comment]
abrt.pot pushed.

**Comment by ernestask** [comment]
Skeletons removed as well.

**Comment by Jibec** [comment]
configuration is done: 
https://translate.stg.fedoraproject.org/projects/abrt/abrt/


LINGUAS will be updated by Weblate

PO files will be updated by Weblate when POT is updated

Weblate will use Git Squash by author to limit the number of commits

I enabled language consistency between your components (if you add a 
language in one component, it will add it to all components)
