### ISSUE TITLE
unable to report bugs to Fedora 32 release

### ISSUE THREAD

**Issue by pnemade** [abrt/abrt#1447]
I have installed latest available Fedora 32 Workstation iso which have abrt-2.14.0-2.fc32.x86_64 package. This system gives notification that tracker-miners package got crash. I tried to report it but I got "The release 'Fedora-32-x86_64' is not supported by the Retrace server".

What need to be fixed so that I can report bugs?

**Comment by mkutlak** [comment]
Can you post the version of `tracker-miners` and contents of `/etc/os-release`?

Anyway, the reporting will fail for Fedora 31+ (Fedora 32, rawhide), because [retrace.fedoraproject.org](retrace.fedoraproject.org) still doesn't support `zstd` compression. (issue https://github.com/abrt/retrace-server/issues/258)

If you want to report the bug, you will have to choose local retracing:
```
Ok to upload core dump? (It may contain sensitive data). If your answer is 'No',
a stack trace will be generated locally. (It may download a huge amount of data).
[y/N/f/e]
```
Choose no (N).

The process will then download debuginfos locally, so abrt can gather traceback from the crash.

**Comment by pnemade** [comment]
tracker-miners-2.3.1-4.fc32.x86_64

```
 [test@localhost ~]$ cat /etc/os-release 
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

Thanks, I will try local retracing.

**Comment by mkutlak** [comment]
> tracker-miners-2.3.1-4.fc32.x86_64
> 
> ```
>  [test@localhost ~]$ cat /etc/os-release 
> NAME=Fedora
> VERSION="32 (Workstation Edition)"
> ID=fedora
> VERSION_ID=32
> VERSION_CODENAME=""
> PLATFORM_ID="platform:f32"
> PRETTY_NAME="Fedora 32 (Workstation Edition)"
> ANSI_COLOR="0;34"
> LOGO=fedora-logo-icon
> CPE_NAME="cpe:/o:fedoraproject:fedora:32"
> HOME_URL="https://fedoraproject.org/"
> DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
> SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
> BUG_REPORT_URL="https://bugzilla.redhat.com/"
> REDHAT_BUGZILLA_PRODUCT="Fedora"
> REDHAT_BUGZILLA_PRODUCT_VERSION=32
> REDHAT_SUPPORT_PRODUCT="Fedora"
> REDHAT_SUPPORT_PRODUCT_VERSION=32
> PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
> VARIANT="Workstation Edition"
> VARIANT_ID=workstation
> ```

Thank you, I've added `Fedora 32` to `retrace.fedoraproject.org`.

**Comment by pnemade** [comment]
Thank you @mkutlak for your quick response
