### ISSUE TITLE
ABRT very frequently fails to report crashes, and does not allow reporting failure to report

### ISSUE THREAD

**Issue by mcatanzaro** [abrt/abrt#1449]
It's very common for ABRT bug reporting process to fail. For example:

![Screenshot from 2020-02-21 14-44-17](https://user-images.githubusercontent.com/1424966/75070838-b1fc3400-54b9-11ea-990d-3abae2710208.png)

Or, more commonly:

![Screenshot from 2020-02-21 14-52-00](https://user-images.githubusercontent.com/1424966/75070852-ba546f00-54b9-11ea-8e6a-0912f45a66b1.png)

This results in a very poor user experience. Users consider ABRT to be unreliable and buggy when this happens. When ABRT is unable to successfully report an issue, it should be possible to report the bug against ABRT itself for further investigation as to why ABRT was unable to report the issue. It might also be useful to gather metrics about how many crashes ABRT is able to successfully report vs. how many reports end in failure; I suspect the percentage of failures will be quite high.

**Comment by msrb** [comment]
This problem should be fixed in the latest ABRT update: `abrt-2.17.1-1.fc38` -- it's already in f38 stable.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/abrt/abrt/issues/1449#issuecomment-1617674010

@msrb, do you mean that a user can report a failure to generate a backtrace?
