### ISSUE TITLE
No log on Processing finished page

### ISSUE THREAD

**Issue by mcatanzaro** [abrt/abrt#1451]
I managed to report a gnome-terminal-server crash, but on the success page I see nothing:

![Screenshot from 2020-02-21 15-06-27](https://user-images.githubusercontent.com/1424966/75071868-deb14b00-54bb-11ea-9eb9-3d3d920fe491.png)

Never seen this one before.

**Comment by mgrabovsky** [comment]
I see a scrollbar. Is there anything later on in the output?

**Comment by mcatanzaro** [comment]
No, I scrolled to the bottom and there's nothing there.

**Comment by mgrabovsky** [comment]
I _think_ this might be fixed (we fixed some potentially related issues in libreport). Have you encountered this recently?

**Comment by mcatanzaro** [comment]
No, I think I only saw this once.

**Comment by mgrabovsky** [comment]
OK, I'm closing this for the time being.
