### ISSUE TITLE
Retrace server should not fail

### ISSUE THREAD

**Issue by mcatanzaro** [abrt/abrt#1457]
When reporting a crash, ABRT first tries to use the retrace server. This usually takes a long time (10-15 minutes) and almost always fails, resulting in a poor user experience. Then, once it fails, ABRT falls back to installing debuginfo locally and generating the backtrace locally. This installs a huge amount of debuginfo, but it's much faster and seems more reliable.

ABRT should either (a) skip the retrace server step entirely, given that it usually fails, or (b) improve so that it doesn't fail.

**Comment by ernestask** [comment]
“Almost always fails”? Stop using abrt as a catch-all for issues and create an issue for retrace-server if you have some specific complaints.

Too broad, closing.

**Comment by mcatanzaro** [comment]
Is there a separate bugtracker somewhere for the retrace server?

I'm not sure how a more specific bug report would be possible. All we get is a generic error message saying "retrace failed" with basically no useful details. Then ABRT deletes the problem directory almost right away, so I don't have that anymore either. I can try to upload a problem directory next time I see this happen, if ABRT leaves it alone long enough for me to do so, but that's all I can think to do besides say "retrace failed." To get better bug reports we'd need to include details in the error message, right?

**Comment by ernestask** [comment]
It’s literally the retrace-server repository. If you can reproduce this consistently, then I can only suggest bumping the storage limit in the ABRT config and trying again until the underlying issue is resolved.

**Comment by mcatanzaro** [comment]
Moved to: https://github.com/abrt/retrace-server/issues/303
