### ISSUE TITLE
[question] Reporting crashes on GitHub issues page

### ISSUE THREAD

**Issue by protonesso** [abrt/abrt#1458]
Hi, I'm interested in ABRT tool, especially using it to test our Linux distribution and fix bugs. We are using GitHub issues to track bugs. Can ABRT report crashes on GitHub or we should use our own bugzilla?

**Comment by ernestask** [comment]
We currently only support Bugzilla and MantisBT, but we’re looking into providing GitLab support in the near future. GitHub is not on the roadmap at the moment.

If you’re interested in writing a GitHub reporter for us, that would definitely speed things up.

**Comment by xsuchy** [comment]
The reporter is in libreport package. And e.g. Mantis reporter is here https://github.com/abrt/libreport/blob/master/src/plugins/reporter-mantisbt.c - you can get inspired by that code.

**Comment by protonesso** [comment]
Thanks for info!
