### ISSUE TITLE
Allow reporting tainted kernel oopses

### ISSUE THREAD

**Issue by djuarezg** [abrt/abrt#1492]
You can deploy your own https://github.com/abrt/faf server, which would mean that reporting tainted kernel oopses should be possible in this case.

* Trying to report to https://abrtanalytics.web.cern.ch/faf:
```
[root@c7juareztest ~]# abrt-cli report 81d0dfa2d5df0de597ef857445d5905ec75f7cfb -v 
A kernel problem occurred, but your kernel has been tainted (flags:POE). Explanation:
P - Proprietary module has been loaded.
O - Out-of-tree module has been loaded.
E - Unsigned module has been loaded.
Kernel maintainers are unable to diagnose tainted reports.

Problem '/var/spool/abrt/vmcore-127.0.0.1-2020-05-29-17:15:12' cannot be reported
```

Using `-u` fails as well:

```
[root@c7juareztest ~]# abrt-cli report 81d0dfa2d5df0de597ef857445d5905ec75f7cfb -u
Looking for kernel package
Kernel package kernel-3.10.0-1127.8.2.el7.x86_64 found
Problem comes from unpackaged executable. Unable to create uReport.
```

**Comment by djuarezg** [comment]
@ernestask Ha, just updating at the same time.

Manual reporting and autoreporting for this case does not seem to work as expected.

**Comment by ernestask** [comment]
> EDIT: OK, so the problem is that CentOS 7 abrt version is just too old...

Yeah… That’s going to be a problem. There is simply no way we are going to maintain that code upstream. Building the latest upstream code in CentOS 7 might also be non-trivial (I can already see at least json-c being a smidge too old, which is needed for satyr, which provides satyr-devel, which is needed for libreport, because no repository provides that devel package, AFAIK), so the options are limited here.

Seems that `abrt-action-save-kernel-data` does not write the one file that is checked when reporting (`package`), so it would be trivial to fix in theory, but that would only happen per a Red Hat customer’s request.

I have no choice but to close this, sorry.

**Comment by djuarezg** [comment]
@ernestask I am using CentOS 8 which has a recent version. I provoke a kernel panic as it follows but this still does not allow me to report it:

I cause a kernel panic
```
echo c > /proc/sysrq-trigger
# Node blocks and reboots
[root@c8juareztest2 ~]# abrt-cli list
id 755572543edc6d404c61eaf879a639742e6204ec
reason:         BUG: unable to handle kernel NULL pointer dereference at 0000000000000000
time:           Thu 04 Jun 2020 12:07:10 PM CEST
uid:            0 (root)
count:          1
Directory:      /var/spool/abrt/vmcore-127.0.0.1-2020-06-04-12:06:44

id 88f2f09008310651cef20d4e6262bb88942ca309
reason:         __nanosleep(): sleep killed by SIGSEGV
time:           Thu 04 Jun 2020 12:05:45 PM CEST
cmdline:        sleep 10m
package:        coreutils-8.30-6.el8_1.1
uid:            0 (root)
count:          1
Directory:      /var/spool/abrt/ccpp-2020-06-04-12:05:45-1693
Reported:       https://abrtanalytics.web.cern.ch/faf/reports/bthash/49812f9f2940c5ea55c2ab7ebe395c7358f14dd4
[root@c8juareztest2 ~]# abrt-cli report 755572543edc6d404c61eaf879a639742e6204ec
1 Attach crash data to an existing Red Hat support case
  Provide Red Hat Support with crash details

2 Ask Red Hat Support for help
  Create new Red Hat Support case - I would like to be contacted by Red Hat Support

3 Submit anonymous crash report
  Submit anonymous crash report - I do not want to be contacted by Red Hat Support

Select a workflow to run:  3
Problem comes from unpackaged executable. Unable to create uReport.
('report_uReport' exited with 1)
```

**Comment by ernestask** [comment]
/me coughs.

abrt-action-ureport consults /etc/libreport/plugins/ureport.conf. You would need to set `ProcessUnpackaged` there as well.

**Comment by djuarezg** [comment]
That is the case, I completely forgot to mention it, but hence my surprise.
