### ISSUE TITLE
documentation typo "/vart"

### ISSUE THREAD

**Issue by Nick-Levinson** [abrt/abrt#1497]
At https://abrt.readthedocs.io/en/latest/debugging.html#abrt-log-messages (as accessed 4-1-20 & 6-3-20) the second choice is

grep abrt /vart/log/messages

but it probably should read

grep abrt /var/log/messages

As a test, I tried changing directory to /vart and failed.

**Comment by mgrabovsky** [comment]
Thanks for your report. We have just pushed an update to the documentation.
