### ISSUE TITLE
BlackListPaths does not prevent dump directory creation upon first detection of the executable on the BlackListPaths

### ISSUE THREAD

**Issue by jimferr** [abrt/abrt#1540]
The first time an abort occurs on a binary from the BlackListPaths the dump directory is created.  Later on in the processing it is detected that the binary is on the BlackList and the dump directory is removed.  This only occurs the first time the abort for a given binary occurs and if  abrt/last-via-server contains the path to binary in question.  This is all traceable via looking at the journald log.
As a result at times during that window where the dump directory exist and a periodic check for dumps via abrt-cli list occurs it results in a ‘false positive”.
The following is an excerpt from journald cooberating the issue:
Oct 23 17:54:02 'Name Edited Out' abrt-server[73521]: Blacklisted executable '/usr/bin/repoquery'
Oct 23 17:54:02 'Name Edited Out' abrt-server[73521]: 'post-create' on '/coredumps/sh/abrt/Python-2020-10-23-17:54:02-73298' exited with 1
Oct 23 17:54:02 'Name Edited Out' abrt-server[73521]: Deleting problem directory '/var/spool/abrt/Python-2020-10-23-17:54:02-73298'
Oct 23 17:54:02 'Name Edited Out' abrt-server[73640]: Not saving repeating crash in '/usr/bin/repoquery' 

Linux version 4.1.12-124.43.4.el7uek.x86_64 (mockbuild@) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16.0.3) (GCC) )
abrt version 2.1.11

**Comment by xsuchy** [comment]
This is expected.

The check for BlackListPath happens in PostCreate. This check checks `executable` in a problem dir. But to check it, the problem dir must exists firts. This is not optimal from performance point of view, but save us from implementing the check for each report type separately before we create the directory.
