### ISSUE TITLE
Rephrase Description of services

### ISSUE THREAD

**Issue by michalfabik** [abrt/abrt#1547]
The `Description` field in `init-scripts/abrt-<whatever>.service` currently says what the service _does_ rather than what it _is_. This produces systemd log entries such as: "Stopped Creates ABRT problems from coredumpctl messages." If this is the only place where these descriptions are used, it's probably a non-issue. Otherwise it might be worth fixing.

**Comment by rquarry** [comment]
I believe this issue can be closed due to PR #1627

**Comment by mgrabovsky** [comment]
Looks like it. Thanks for the heads up.
