### ISSUE TITLE
Unable to report an error

### ISSUE THREAD

**Issue by druizz90** [abrt/abrt#1549]
I received an `AttributeError` when reporting a package crash:

![2](https://user-images.githubusercontent.com/32929872/102109129-02bb8f80-3e34-11eb-857a-69ea1ab70190.png)

I explored the class `DNFDebugInfoDownload` and its parent `DebugInfoDownload` (the parent is placed in `'/usr/lib64/python3.9/site-packages/reportclient/debuginfo.py'` in my distribution), and I checked that the attribute `get_package_count` doesn't exist.

After deleting lines https://github.com/abrt/abrt/blob/master/src/plugins/abrt-action-install-debuginfo.in#L161-L162, the error was reported properly.

Since the error happens in a `print` statement, I think that a solution maybe what I did above.

**Version info**:
_python3-3.9.0-1.fc33.x86_64_
_python3-abrt-addon-2.14.5-1.fc33.noarch_
_abrt-tui-2.14.5-1.fc33.x86_64_
_abrt-gui-2.14.5-1.fc33.x86_64_
_abrt-desktop-2.14.5-1.fc33.x86_64_
_abrt-cli-2.14.5-1.fc33.x86_64_

**Comment by mgrabovsky** [comment]
We are tracking this issue in a [downstream report](https://bugzilla.redhat.com/show_bug.cgi?id=1906405) and we have already pushed an update fixing this. Please see [comment 13](https://bugzilla.redhat.com/show_bug.cgi?id=1906405#c13) in the above bug report on instructions how to test the update.
