### ISSUE TITLE
Links to ABRT Analytics does not work

### ISSUE THREAD

**Issue by xsuchy** [abrt/abrt#1552]
In
  https://bugzilla.redhat.com/show_bug.cgi?id=1911553
there is link 
  https://retrace.fedoraproject.org/faf/reports/bthash/11da53a474acdcc9d54c5b21759a6ad3eb0d6085/
which does not work.
And 
```
faf=# select * from reportbthashes where hash='11da53a474acdcc9d54c5b21759a6ad3eb0d6085';
 type | hash | backtrace_id 
------+------+--------------
(0 rows)
```
and even
```
cd  /srv/faf/reports
grep -r 11da53a474acdcc9d54c5b21759a6ad3eb0d6085 .
```
returns nothing.
So it sems that the uReport actually never reached ABRT analytics.

**Comment by mgrabovsky** [comment]
There seems to have been a problem with processing incoming reports from Fedora on retrace.fp.org. I ran some scripts yesterday and all seems to be fine now. For instance, I submitted [a report](https://retrace.fedoraproject.org/faf/reports/28315/) from will-crash today which went through just fine.

The report relating to rhbz#1911553 mentioned above is over a week old so it is gone, but new reports should be processed correctly.

Closing this as resolved.
