### ISSUE TITLE
bad "signalize" wording in abrt-action-analyze-oops

### ISSUE THREAD

**Issue by skierpage** [abrt/abrt#1563]
At startup, KDE indicated a crash in SDDM. The abrt GUI showed
> The backtrace does not contain enough meaningful function frames to be reported. It is annoying but it does not necessarily signalize a problem with your computer. ABRT will not allow you to create a report in a bug tracking system but you can contact kernel maintainers via e-mail.

This is misuse of the obscure term "signalize"  (_to make conspicuous : distinguish, mark_). Change this to the more correct "indicate" which English speakers use roughly 10,000 times more often.

it's an easy change to the string in src/plugins/abrt-action-analyze-oops.c.

**Comment by skierpage** [comment]
The string also appears as the `msgid` for a translated `msgstr` in 66 `.po` files. I don't understand the po translation system so I'm not confident in my patch.

**Comment by michalfabik** [comment]
Hi,  
yeah, actually the whole thing could use some good proofreading. You don't have to deal with the `.po` files. The Translation team updates those in Weblate and a PR is opened once in a while. Thanks.

**Comment by msrb** [comment]
Thanks! :)
