### ISSUE TITLE
unhandled python exception in rhts-report-result 

### ISSUE THREAD

**Issue by g0dd4rd** [abrt/abrt#1623]
python[192517]: detected unhandled Python exception in '/bin/rhts-report-result'
sudo[185373]: pam_unix(sudo:session): session closed for user root
abrt-server[192519]: Package 'restraint-rhts' isn't signed with proper key
abrt-server[192519]: 'post-create' on '/var/spool/abrt/Python3-2022-09-26-05:35:24-192517' exited with 1
abrt-server[192519]: Deleting problem directory '/var/spool/abrt/Python3-2022-09-26-05:35:24-192517'

rhel 9.0, x86_64 from journalctl

**Comment by mgrabovsky** [comment]
This looks like a bug in [rhts](/beaker-project/rhts). You should report the problem there.
