### ISSUE TITLE
Error saving event 'report_Bugzilla' configuration to keyring

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#163]
Opened '20110317T16:42:06' by vbenes as https://fedorahosted.org/abrt/ticket/172

can see this error in window
Empty login or password, please check /etc/abrt/plugins/Bugzilla.conf

and an error in terminal:
.. Error saving event 'report_Bugzilla' configuration to keyring

**Comment by xsuchy** [comment]
@jfilak what is status of this issue?
