### ISSUE TITLE
Select reporter in abrt-cli by a number combination instead of y/N question

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#183]
Opened '20110401T11:50:23' by mnowak as https://fedorahosted.org/abrt/ticket/194

Ref: https://fedoraproject.org/wiki/Test_Day:2011-03-31_ABRT_Retrace_Server#cite_note-10

"I would prefer to be able to select reporter by e.g. number (or combination of numbers) and not to cycle Y/N through all available reporters."

**Comment by ernestask** [comment]
I guess this has been fixed with https://github.com/abrt/libreport/commit/df4141e4ec03089cb3018e40434f8d94edb7970e.
