### ISSUE TITLE
implement reporting by component

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#290]
Opened '20110727T08:40:04' by npajkovs as https://fedorahosted.org/abrt/ticket/325

abrt-cli report -c kernel

**Comment by ernestask** [comment]
abrt-cli-ng can already do that and has since replaced abrt-cli (https://github.com/abrt/abrt/commit/bd0315b9b24c644b388abe4ae4b8ae2cdaec585b).

Although it should be decided whether we want to keep the pattern-matching thing that we have or introduce switches like the afforementioned `-c`.
