### ISSUE TITLE
Clean up doc/

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#383]
Opened '20120221T13:27:37' by mmilata as https://fedorahosted.org/abrt/ticket/457

Apart from manual pages, the doc/ directory contains files which are mostly out-of-date and document the old version of ABRT:
{{{
coding-style
design
how-to-test
implementation
interpreted-languages (this one seems quite up-to-date)
plugins-howto
TODO_crash_dump_fields
}}}

These files should probably by either updated or removed altogether.

**Comment by xsuchy** [comment]
Too general.
