### ISSUE TITLE
Implement both variants of apology dialog

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#436]
Opened '20120402T14:16:15' by jmoskovc as https://fedorahosted.org/abrt/ticket/516

**Comment by hadess** [comment]
I'm guessing this is about a better notification for crash reports? This has been implemented in abrt-applet. See commit 5a2141eae7f6d5ae220fe17802340bc16cd6dde8

**Comment by jfilak** [comment]
You are right!
