### ISSUE TITLE
investigate how to detect unhandled JAVA exceptions

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#462]
Opened '20120618T08:26:27' by jmoskovc as https://fedorahosted.org/abrt/ticket/592
- discussing with ptisnovs, so fat we have two ideas:
- override the Exception or Throwable classes
- implement python like logic into JVM where user can override the exception hook
- the first option is quite dangerous and can destabilize the whole JAVA stack
- the second option will require changes in JVM and might not be accepted by upstream and by the Sun JAVA

**Comment by xsuchy** [comment]
We are handling java exceptions for some time. Closing.
