### ISSUE TITLE
applet doesn't show foreign problems

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#507]
Opened '20120820T07:56:10' by jmoskovc as https://fedorahosted.org/abrt/ticket/691

after start, applet chceks for crashes which happend when the applet wasn't running and shows notification if a new crash exist. However this only works for crashes readable by user who is running the applet

**Comment by hadess** [comment]
This now works for users who have enough rights (through PolicyKit) to read those reports. Non-administrator users shouldn't see crashes from other users, or which they cannot act upon.

See commits 4ee057834e4c9a8438c195c7ff79095cf3f64249 and f8bee610db33c138c67d7f4675f0e063debbfb2e
