### ISSUE TITLE
Drop btserver.cgi logic from ABRT

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#520]
Opened '20120914T13:06:33' by mtoman as https://fedorahosted.org/abrt/ticket/730

ABRT server has overtaken the functionality of deduplicator, thus btserver.cgi is no longer required.

F16 does not use ABRT server and thus we need to keep the server side online until F16 dies. The client dedup code may however be removed from upstream git.

**Comment by ernestask** [comment]
Obsolete as of 31f657431ee46ac53559dc43db77567a1a63ef8b.
