### ISSUE TITLE
add "create ticket" to the failed testsuite runs

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#542]
Opened '20121105T14:51:19' by jmoskovc as https://fedorahosted.org/abrt/ticket/835
- when a testsuite fails, there should be an easy way, to create a ticket for with and attach the logs, so it's not forgotten

**Comment by xsuchy** [comment]
When we implement https://github.com/abrt/abrt/issues/540 then developer should be able to fix it immediately and not even create issue. So we do not need this.
