### ISSUE TITLE
get ureport to suse

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#546]
Opened '20121105T15:23:48' by jmoskovc as https://fedorahosted.org/abrt/ticket/847
- either integrate it with their bug reporting solution (if there is any)
- or try to push ABRT to Suse (much better ;)) with a minimal functionality, just to send the ureport (can help to extend the ABRT community outside redhat!!)
- note: they use journald to catch the cores, so we need to modify the ccpp-hook

**Comment by xsuchy** [comment]
not going to happen without external contribution.
