### ISSUE TITLE
pull the suse packages to ABRT server

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#547]
Opened '20121105T15:26:14' by jmoskovc as https://fedorahosted.org/abrt/ticket/848
- learn their infrastructure
- write the scripts to pull the packages
- write the scripts to pull the components
- we will need some mapping between Fedora and Suse components
- teach ABRT server to communicate with their bz (later)
- split to separate tickets?

**Comment by xsuchy** [comment]
We do not have space even for all Fedora arches. I am very afraid this will never happen because of lack of money.
