### ISSUE TITLE
don't rely on EAGAIN errno while reading from nonblocking GIOChannel

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#559]
Opened '20121115T14:59:38' by jfilak as https://fedorahosted.org/abrt/ticket/872

The g_io_chanel_read_chars() [1] function returns G_IO_STATUS_AGAIN[2] in case where reading will be blocking, the errno approach is not supported by GLib.

1: http://developer.gnome.org/glib/2.32/glib-IO-Channels.html#g-io-channel-read-chars
2: http://developer.gnome.org/glib/2.32/glib-IO-Channels.html#GIOStatus

**Comment by mzidek-gh** [comment]
The code now uses G_IO_STATUS_AGAIN, not errno. Closing.
