### ISSUE TITLE
binary files inaccessible via dbus API

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#575]
Opened '20121205T14:24:52' by rmarko as https://fedorahosted.org/abrt/ticket/914

{{{
In [6]: prox._dbus_call('GetInfo', x, ['coredump'])
Out[6]: dbus.Dictionary({dbus.String(u'coredump'): dbus.String(u'[Invalid UTF-8]')}, signature=dbus.Signature('ss'))
}}}

base64?

archives like etc_X11_xorg_conf_d.tar.gz should be handled as well

**Comment by xsuchy** [comment]
Insufficient information. Closing.
