### ISSUE TITLE
start versionin the libraries

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#603]
We still have soname 0.0.1 and already ran into a few problems when changing API/ABI and not changing the soname.

**Comment by xsuchy** [comment]
Related to https://github.com/abrt/libreport/issues/129

**Comment by xsuchy** [comment]
note that in ABRT package we have:
/usr/lib64/libabrt_dbus.so.0.0.1  /usr/lib64/libabrt_gui.so.0.0.1  /usr/lib64/libabrt.so.0.0.1
