### ISSUE TITLE
Need a way to limit the size of sosreport data

### ISSUE THREAD

**Issue by dvlasenk** [abrt/abrt#620]
We have a commented-out sosreport run on post-create:
# EVENT=post-create

```
    nice sosreport --tmp-dir "$DUMP_DIR" --batch \
            --only=anaconda --only=bootloader --only=devicemapper \
            --only=filesys --only=hardware --only=kernel --only=libraries \
            --only=memory --only=networking --only=nfsserver --only=pam \
            --only=process --only=rpm -k rpm.rpmva=off --only=ssh \
            --only=startup --only=yum --only=general --only=x11 \
            >sosreport.log 2>&1 \
```

...

Sometimes sosreport generates insane amounts of data. For example, users report 17Gb of logs from libvirt. This makes sosreport run way too slow, overfills /tmp, etc...
Need a way to tell sosreport to avoid doing that.

**Comment by mkutlak** [comment]
sosreport has a `--log-size` option. See [sosreport/wiki/Plugin-options#global-options](https://github.com/sosreport/sos/wiki/Plugin-options#global-options)



```
--log-size, specify a limit for per-log file data collection
```

By default the limit is set to 25MiB per log file.


If anyone feels that we should adjust the size, feel free to reopen this issue.
