### ISSUE TITLE
enable ignoring of foreign problems from notification bubbles

### ISSUE THREAD

**Issue by jfilak** [abrt/abrt#684]
Both uuid and duphash elements are not accessible for a foreign user. There is a couple of possible solutions:

* Crash signal could contain these element values.
* We can somehow refine access control because several of standard problem elements may be accessible for reading for other users. abrt-dbus could be used as a problem data access point or we can revive effort to develop ABRT server.
* ...

https://bugzilla.redhat.com/show_bug.cgi?id=953927#c5

**Comment by hadess** [comment]
"Foreign" problems are now notified upon, but only for users with enough rights to act upon them. Should we consider this fixed?

**Comment by jfilak** [comment]
This issue was fixed a year ago and I forgot to close. Thanks!
