### ISSUE TITLE
Please encypt the abrt reports

### ISSUE THREAD

**Issue by Netbulae** [abrt/abrt#782]
As descirbed on the page below, intelligence services or anyone who can sniff your network traffic can use the automatic bug reports to profile your system and find vulnerabilities. 

http://www.spiegel.de/international/world/the-nsa-uses-powerful-toolbox-in-effort-to-spy-on-global-networks-a-940969-2.html

From what I've been reading I cannot deduce if the abrt bug reports are encrypted but I don't think they are.

Just to add, I know the reporting uses SSL as default but this doesn't protect against MITM attacks and other flaws in the SSL protocol.

**Comment by xsuchy** [comment]
We have SSL, and if if you are afraid of MITM then you can use DNSSEC - retrace.fedoraproject.org is using it.
