### ISSUE TITLE
ABRT should consider processes with locked memory security sensitive

### ISSUE THREAD

**Issue by lkundrak** [abrt/abrt#796]
I was quite surprised when I noticed keepassX reports from ABRT. It's a password manager and thus very likely to contain secrets in tracebacks.

A good way to tell a secret manager from other processes is by looking whether it has any memory locked (VmLck != 0 kB in /proc/<pid>/status).

Such process should either be removed from ABRT consideration or treated as potentially containing very sensitive information.

**Comment by jfilak** [comment]
Good point. We will definitely take a closer look in to this. At first glance, I would make crashes of such processes not-reportable or rather introduce a new option that would control this behaviour (ignore such process vs. make the crash not reportable).

By the way, I would expect a password manager application being not-dumpable (prctl,  PR_SET_DUMPABLE).
