### ISSUE TITLE
Security: Remove remote retracing

### ISSUE THREAD

**Issue by hadess** [abrt/abrt#834]
As mentioned in issue #832 , ABRT shouldn't be uploading users' core dumps to an unaudited service, especially one that will need to manipulate potentially tampered data.

Jakub requested comments from the Fedora security mailing-list:
https://lists.fedoraproject.org/pipermail/security/2014-August/001969.html

**Comment by xsuchy** [comment]
The retrace-server service on retrace.f.o is disabled. We are now using podman for retracing. IMO this is good-enough.
Unless there is some specific steps, I am afraid I cannot do anything. Closing. Feel free to dispute.

**Comment by ernestask** [comment]
This is not even remotely related to what you’re talking about. There should be no code that even attempts to upload core dumps for remote retracing.

**Comment by ernestask** [comment]
And the fact that we use podman *in* retrace-server does not mean that retrace-service is disabled.
