### ISSUE TITLE
Find a substitute for GtkStatusIcon

### ISSUE THREAD

**Issue by sorki** [abrt/abrt#836]
DEBUG: applet.c: In function 'hide_icon':
DEBUG: applet.c:572:5: error: 'gtk_status_icon_set_visible' is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h:151) [-Werror=deprecated-declarations]
DEBUG:      gtk_status_icon_set_visible(ap_status_icon, false);
DEBUG:      ^
DEBUG: applet.c: In function 'on_menu_popup_cb':
DEBUG: applet.c:715:17: error: 'gtk_status_icon_position_menu' is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h:160) [-Werror=deprecated-declarations]
DEBUG:                  gtk_status_icon_position_menu,
DEBUG:                  ^
DEBUG: applet.c: In function 'create_status_icon':
DEBUG: applet.c:842:6: error: 'gtk_status_icon_new_from_icon_name' is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h:92) [-Werror=deprecated-declarations]
DEBUG:       GtkStatusIcon *icn = gtk_status_icon_new_from_icon_name("abrt");
DEBUG:       ^
DEBUG: applet.c: In function 'show_icon':
DEBUG: applet.c:858:5: error: 'gtk_status_icon_set_tooltip_text' is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h:137) [-Werror=deprecated-declarations]
DEBUG:      gtk_status_icon_set_tooltip_text(ap_status_icon, tooltip);
DEBUG:      ^
DEBUG: applet.c:859:5: error: 'gtk_status_icon_set_visible' is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h:151) [-Werror=deprecated-declarations]
DEBUG:      gtk_status_icon_set_visible(ap_status_icon, true);
DEBUG:      ^

**Comment by jfilak** [comment]
@allanday I wanted to port abrt-applet to GNotification, but I don't know how to set 'desktop-entry' hint required for Notification in System Settings [1]. 

1: https://wiki.gnome.org/Initiatives/GnomeGoals/NotificationSource

**Comment by hadess** [comment]
That was done in a330accc0929e42d6226ed99ac3cb28d952f70ef
