### ISSUE TITLE
Log lines dumper

### ISSUE THREAD

**Issue by jfilak** [abrt/abrt#864]
Reimplement this https://github.com/abrt/abrt/commit/fd41be88b411cd83c895553ea4e9216836b167c4 in C and use a much more sophisticated approach.

**Comment by jfilak** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1170835

**Comment by xsuchy** [comment]
I think that current implementation is good-enough(tm). Not going happen, unless it is backed up by good reasoning.
