### ISSUE TITLE
abrt-ccpp writes entire coredump, slow for large crashes

### ISSUE THREAD

**Issue by matthewatabet** [abrt/abrt#872]
abrt-ccpp seems to block until the entire coredump is written to disk.
This can be slow for larger applications (>18gb in memory).
It would be great if the hook gathered the coredump in ram and then forked to write it to disk, allowing the crashing process to exit sooner.

**Comment by xsuchy** [comment]
Since abrt-ccpp is obsoleted and replaced by coredump-ctl, there is zero chance we will work on this. Closing.

**Comment by DagNygren** [comment]
So how do you limit the size of the dumped data using coredump-ctl then?
