### ISSUE TITLE
Strip CPU and PID from kernel warnings

### ISSUE THREAD

**Issue by nwnk** [abrt/abrt#879]
Consider the following reports:

https://bugzilla.redhat.com/show_bug.cgi?id=1137025
https://bugzilla.redhat.com/show_bug.cgi?id=1148094

I would have expected these to be considered duplicates of the same issue (same function, same line number, close enough to same kernel version, etc).  If the CPU and PID here are what's confusing the duplicate detection we ought to just strip them out first: the PID will change on pretty much every report, and the CPU you happen to run on almost never matters.

**Comment by xsuchy** [comment]
No answer, so closing as invalid.
