### ISSUE TITLE
Support for libappindicator

### ISSUE THREAD

**Issue by donniezazen** [abrt/abrt#888]
Fedora 22 would feature Plasma 5. Plasma 5 has dropped the support for XEmbed based system tray. abrt gui would not be usable in Fedora 22 running Plasma 5 without a system tray icon to open and report bugs via abrt.

http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/
http://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/

**Comment by hadess** [comment]
What's libappindicator have to do with KDE?

**Comment by donniezazen** [comment]
@hadess libappindicator is an implementation of KStatusNotifierItems by Ubuntu guys. It provides GTK+ apps access to the system tray used in KDE and Unity.

There are other options too but libappindicator is obviously the most popular one.

https://github.com/jjk-jacky/statusnotifier
https://github.com/encharm/libsystemtray

**Comment by hadess** [comment]
The status icon is now gone from the applet. See commit a330accc0929e42d6226ed99ac3cb28d952f70ef

We only use notifications now.
