### ISSUE TITLE
Don't run elfutils/gdb as root

### ISSUE THREAD

**Issue by hadess** [abrt/abrt#890]
Similarly to this systemd bug:
https://bugs.freedesktop.org/show_bug.cgi?id=87354

We probably don't want ABRT to run either elfutils or gdb based code as root, as it could be a security issue.

**Comment by xsuchy** [comment]
I just tried this and `abrt gdb` is run under unprivileg user.

**Comment by mzidek-gh** [comment]
Maybe it was already fixed in commit 8f924520e45a557151e689c3feee569cfde6828d
