### ISSUE TITLE
Capture unpackaged crashers by default

### ISSUE THREAD

**Issue by hadess** [abrt/abrt#891]
Unpackaged or unknown to Fedora. This would allow users to gather debugging information for system problems with third-party drivers or applications, and make it easier to discard data about those crashers without dropping to the command-line.

**Comment by jfilak** [comment]
@hadess I'm not sure what you mean by the last sentence. I guess you want ABRT to delete a journald message that was used to create an abrt problem, right? So *gnome-abrt* should become an unofficial GUI for *coredumpctl*, right?

**Comment by hadess** [comment]
I'd want to remove the journald entries if the abrt entry was removed as well. For example, being able to remove development crashers that I already handled locally.

But the main goal would be for unpackaged crashers to appear in the UI, so it was possible to analyse them and identify them, even for third-party applications and utilities.

**Comment by jfilak** [comment]
OK. I had to ask because such a thing is not possible now. ABRT doesn't execute any hook when deleting a problem, it just remove the related problem directory.

**Comment by hadess** [comment]
Being able to show it would be a first step, being able to delete it from the list (eg. from the view) would the 2nd one. I don't even know if one can remove core dumps from journald right now (we might not be able to, as it would modify the integrity of previous logs, break audit).

**Comment by jfilak** [comment]
You can at least delete a coredump related to a particular journal message because systemd-coredump stores coredump files outside the journal.

**Comment by mtoman** [comment]
Even though the change is already implemented I need to say this is a **bad** idea. I can not see a single benefit (the suggested gui-frontend-to-coredumpctl is absolutely out of scope of the project). On the other hand this will create tons of unreportable entries in ABRT GUI that are only going to confuse users.

**Comment by mbrysa** [comment]
Automated Bug **Reporting** Tool - who are you going to report crashes of third-party apps to?
I'm for reverting this.

**Comment by hadess** [comment]
If the goal is not to help developers and QE, then we can rip out half of gnome-abrt. We even made design decisions based on the fact that it wasn't only a bug reporting tool for end users.
