### ISSUE TITLE
Notification responses aren't registered in KDE

### ISSUE THREAD

**Issue by donniezazen** [abrt/abrt#892]
![snapshot28](https://cloud.githubusercontent.com/assets/841656/5469601/83157190-8603-11e4-986f-a6f6408a51af.png)

The notification has two options Report or Ignore. If you click them they go away like in the picture and no action is taken.

**Comment by donniezazen** [comment]
Looks like the issue has been resolved.

**Comment by jfilak** [comment]
I love KDE developers. I asked them to fix their notification server and they did it. Can you feel the difference? I wish all desktop developers were the same as KDE developers.
