### ISSUE TITLE
will_stackoverflow forces abrt to consume one entire cpu for a very long time

### ISSUE THREAD

**Issue by cristi1979** [abrt/abrt#896]
Running will_stackoverflow will force abrt to execute the following:

    18674 ?        Ss     0:00 /usr/sbin/abrtd -d -s
    31106 ?        S      0:00  \_ abrt-server -s
    31107 ?        S      0:00      \_ /usr/libexec/abrt-handle-event -i -e post-create -- /var/spool/abrt/ccpp-2015-01-13-08:32:49-31104
    31134 ?        S      0:00          \_ /bin/sh -c if grep '^TracerPid:[[:space:]]*[123456789]' proc_pid_status >/dev/null 2>&1; then             # We see 'TracerPid: <nonzero>" in /proc/PID/st
    31138 ?        R      2:21              \_ abrt-action-generate-core-backtrace

abrt-action-generate-core-backtrace process seems to read something for ever? :

    # strace -f -p 31138
    Process 31138 attached
    pread(3, "[\5@\0\0\0\0\0", 8, 1016648)  = 8
    pread(3, "[\5@\0\0\0\0\0", 8, 1016664)  = 8
    pread(3, "[\5@\0\0\0\0\0", 8, 1016680)  = 8

I have no idea when this will stop, I will update the issue if I can find out.

Packages installed:

    # rpm -qa | grep abrt | sort
    abrt-2.1.11-12.0.1.el7.x86_64
    abrt-addon-ccpp-2.1.11-12.0.1.el7.x86_64
    abrt-addon-kerneloops-2.1.11-12.0.1.el7.x86_64
    abrt-addon-pstoreoops-2.1.11-12.0.1.el7.x86_64
    abrt-addon-python-2.1.11-12.0.1.el7.x86_64
    abrt-addon-vmcore-2.1.11-12.0.1.el7.x86_64
    abrt-addon-xorg-2.1.11-12.0.1.el7.x86_64
    abrt-cli-2.1.11-12.0.1.el7.x86_64
    abrt-console-notification-2.1.11-12.0.1.el7.x86_64
    abrt-libs-2.1.11-12.0.1.el7.x86_64
    abrt-python-2.1.11-12.0.1.el7.x86_64
    abrt-tui-2.1.11-12.0.1.el7.x86_64

This is the same for el6 also using satyr compiled from el7 sources and abrt from http://copr-be.cloud.fedoraproject.org/results/jfilak/abrt/epel-6-x86_64/.

**Comment by jfilak** [comment]
Thank you for the report! If you have time and want to help us, please compile satyr from rhel7 upstream branch (https://github.com/abrt/satyr/tree/rhel7) and report the results here.

**Comment by cristi1979** [comment]
It's ok with latest version. I tested el6 and el7.
