### ISSUE TITLE
No taskbar entry is created for ABRT Dialog

### ISSUE THREAD

**Issue by donniezazen** [abrt/abrt#913]
ABRT dialog which is presented after a user makes a selection on to report or ignore an issue doesn't create a taskbar entry and opens itself in background. I am using KDE Plasma 5 on Fedora 21.

![snapshot14](https://cloud.githubusercontent.com/assets/841656/6145296/5453d728-b206-11e4-8b29-a117c0efd267.png)

**Comment by hadess** [comment]
This is fixed, as this dialogue was removed in commit 57f4234779b7fbcaeca5c0ed430eeddc5003007e
