### ISSUE TITLE
Use ACLs instead of chown'ing the dump dir

### ISSUE THREAD

**Issue by hadess** [abrt/abrt#915]
This would allow multiple users to access the dump directory, for example, the user for which the crash occurred, and the administrator. Or multiple administrators.

**Comment by jfilak** [comment]
abrt group has access, so put your administrators into abrt group. Or add a special casing for wheel group to https://github.com/abrt/libreport/blob/master/src/lib/dump_dir.c#L1245

**Comment by hadess** [comment]
> abrt group has access, so put your administrators into abrt group.

That doesn't work for existing users, and doesn't use the same mechanism as the rest of the admin functions.

> Or add a special casing for wheel group

Noted.

**Comment by hadess** [comment]
I've posted a patch for libreport to the mailing-list for this.

**Comment by xsuchy** [comment]
Any link for the patch? I am afraid no abrt-devel will work on this any time soon.

**Comment by hadess** [comment]
https://www.mail-archive.com/crash-catcher@lists.fedorahosted.org/msg05097.html

**Comment by hadess** [comment]
It's a potential security issue.
