### ISSUE TITLE
Missing manual pages

### ISSUE THREAD

**Issue by jfilak** [abrt/abrt#922]
- abrt-dump-journal-code
- abrt-save-container-data

**Comment by xsuchy** [comment]
I cannot find the executables abrt-dump-journal-code. But we are missing man page for:

 * abrt-action-save-container-data

**Comment by matejkudera** [comment]
i will by working on this

**Comment by xsuchy** [comment]
Fixed by https://github.com/abrt/abrt/pull/1246
