### ISSUE TITLE
D-Bus interface always uses strings

### ISSUE THREAD

**Issue by hadess** [abrt/abrt#927]
Even for items which should be integers, or mixed types.

It should be:
s NewProblem(a{sv})
not:
s NewProblem(a{ss})

It should be:
a{sv} GetInfo(a, as)
not:
a{ss} GetInfo(a, as)

etc.

**Comment by jfilak** [comment]
Nice idea. Actually I wanted to rework the D-Bus api entirely, I just didn't have time.

**Comment by mzidek-gh** [comment]
I think this is already done. See:
git show 84ccc1c625

It is a big patch, but here is a snippet from doc/problems-service/org.freedesktop.Problems.xml.in:

```
                 <tp:docstring>Creates a new problem and returns it's identifier.</tp:docstring>
 
-                <arg type='a{ss}' name='problem_data' direction='in'>
+                <arg type='a{sv}' name='problem_data' direction='in'>
                     <tp:docstring>
-                        A dictionar
```

Closing this, please re-open if you think some types should be changed.
