### ISSUE TITLE
Remove GetForeignProblems method

### ISSUE THREAD

**Issue by hadess** [abrt/abrt#929]
As added in f0d4c2e67773a00665ad52d6ea3829334e4f0ac9

It is actually a security problem to see other users' problems without authentication. See also bug #926 about leaking information about other users and their crashes.

**Comment by jfilak** [comment]
GetForeignProblems() is used by gnome-abrt for displaying the "System" problems.

**Comment by hadess** [comment]
A dichotomy that we want to remove.

**Comment by jfilak** [comment]
You don't see other's problems, you only see directory names and you cannot deduce anything from those names except timestamp, type and uid of the crash.

**Comment by hadess** [comment]
Which is already a lot of information leaked.

**Comment by jfilak** [comment]
Just for the record, can you please write down a few use cases where you can use that data for something bad? I cannot think of anything.

**Comment by hadess** [comment]
Through the directory listing, you can know that the other person was using their computer at that time, and the type of crash (Java vs. Ccpp).

**Comment by jfilak** [comment]
The same you get from "ps aux", right?

**Comment by xsuchy** [comment]
Unless it is proven to be security issue I think no one will work on this.

**Comment by hadess** [comment]
It is a potential information disclosure problem.
