### ISSUE TITLE
Disable SSLv3

### ISSUE THREAD

**Issue by elad661** [abrt/abrt#937]
https://github.com/abrt/abrt/blob/master/src/plugins/https-utils.c#L219

This should not be enabled. SSLv3 is considered insecure and harmful.

https://en.wikipedia.org/wiki/POODLE

**Comment by jfilak** [comment]
Thanks @elad661. SSLv3 is disable on the server [1]. Let the server maintainers decide what's secure and what not. What do you think? SSLv2 is disable in NSS, SSLv3 is insecure and TLS might be insecure too.

1: https://www.ssllabs.com/ssltest/analyze.html?d=retrace.fedoraproject.org&latest

**Comment by musicinmybrain** [comment]
Disabling SSLv3 on the server should be sufficient to protect against POODLE, assuming that it is never accidentally re-enabled, and that nobody ever uses ABRT with any server other than retrace.fedoraproject.org—but there is no reason to make these assumptions. I cannot see any valid use case where continued SSLv3 support benefits anyone.

**Comment by ernestask** [comment]
The code no longer exists as of https://github.com/abrt/abrt/commit/f1d99e1d7593ab49147268b383cc82acbb0d94c1. libsoup defaults to disabling the SSLv3 fallback.
