### ISSUE TITLE
The notifications should enable opening problem details for unpackaged crashes

### ISSUE THREAD

**Issue by jfilak** [abrt/abrt#941]
<jfilak> hadess: shouldn't abrt-applet offer opening the problem details for crashes of unpackaged programs? The current notifications seems to me useless in those cases :)
<jfilak> hadess: Such a notification doesn't say what crashed and the only thing you can do is to close it :)
<hadess> jfilak, we probably could have it open gnome-abrt with the report in question
<hadess> jfilak, can you see that with aday when he comes back around?
<jfilak> hadess: sure
<hadess> or file a new bug, but that's a good suggestion

**Comment by xsuchy** [comment]
We already have config option for that. And it should work.
