### ISSUE TITLE
[RFE] ability of ignoring a concrete issue

### ISSUE THREAD

**Issue by rfmvh** [abrt/abrt#949]
As Abrt is able to recognize the same issues when they occur repeatedly, it would be great to be able to ignore the whole issue... Some issues happen really often and the fixes can come not very soon. Abrt is reporting it then, again and again, and it doesn't make sense anymore when it has been already reported to BZ.

**Comment by xsuchy** [comment]
ABRT is trying hard to identify duplicates. If there is a duplicate we file it as duplicate and not as a new issue. If we fail to identify duplicate then please let us show two issues which are duplicate but ABRT does not think so. But without hard data, there is nothing we can do.
