### ISSUE TITLE
ABRT settings should be in sync with Privacy settings in Control Center

### ISSUE THREAD

**Issue by Sesivany** [abrt/abrt#966]
Even if I have automatic reporting enabled in ABRT, reports are not reported because it's overrode by settings in Privacy in Control Center. IMHO those two settings should be in sync, otherwise it's very confusing for users.

**Comment by hadess** [comment]
As far as GNOME (and abrt-applet and gnome-abrt), the ABRT setting won't be used. We should have abrt-applet (or whatever ends up replacing it as a background session service) migrate the ABRT option to the problem reporting GSettings.

**Comment by jfilak** [comment]
@hadess Is it OK to modify the problem reporting GSetttings from the abrt configuration dialogue?

**Comment by hadess** [comment]
I don't think so. This migration is just a crutch, and gnome-abrt (an application) shouldn't modify the user's session-wide settings. It would be best if that configuration wasn't there in gnome-abrt's preferences.

**Comment by jfilak** [comment]
I think we have route GNOME users to the new location and we have to tell non-GNOME users how to enable that feature. I am going to add a button opening the panel if gnome-privacy-panel.desktop exists and advise users to run "$ gsettings set ..."  if it doesn't.

**Comment by allanday** [comment]
> I think we have route GNOME users to the new location and we have to tell non-GNOME users how to enable that feature. I am going to add a button opening the panel if gnome-privacy-panel.desktop exists

Sounds fine to me. This could be presented as an "Automatic Reporting" or "Automatic Reporting Preferences" item in the application menu.

**Comment by jfilak** [comment]
@allanday Good idea -> abrt/gnome-abrt#126

I changed my mind and I think it would be better to read/write the problem reporting GSetttings in the abrt configuration dialogue if `gnome-privacy-panel.desktop` does not exist.

**Comment by jfilak** [comment]
Please review #968
