### ISSUE TITLE
Include /etc/os-release in bug reports

### ISSUE THREAD

**Issue by sgallagher** [abrt/abrt#995]
It would be excellent if bugs reported to Bugzilla would include certain tags from /etc/os-release to allow for some simple metrics. Specifically, it would be useful to have bugs filed with the VARIANT tag from /etc/os-release to help get some ideas as to which Fedora Edition the user is running.

**Comment by jfilak** [comment]
Sure, no problem. ABRT already collects this file and uses it to get Red Hat Bugzilla details and so on ( *REDHAT_BUGZILLA_PRODUCT*). Where should we put the VARIANT tag? Should it be included in **Keywords**, **Tags** or **Whiteboard**? I am sure you will want to search by that value and it will not be possible, if we attach the file as is. Perhaps we should include the VARIANT tag in the ABRT server [1] reports too.

1: http://retrace.fedoraproject.org/

**Comment by sgallagher** [comment]
Whiteboard is probably easiest; I think we have to get the BZ admins to add new Keywords. That being said; I think it's easier to search on Keywords. So I'll defer to your judgement there.

Also, contrary to what I said above, it's probably safer for us to tag with VARIANT_ID rather than VARIANT. (VARIANT is the UI-printable version, but we probably want the unquoted VARIANT_ID instead)

Yes, including the VARIANT_ID in the retrace server reports would be excellent. Thanks!

**Comment by jfilak** [comment]
The Bugzilla bugs will looks like this one:
https://partner-bugzilla.redhat.com/show_bug.cgi?id=1256484

I decided to use Whiteboard, because we can simply add more tags there and searching by ";VARIANT_ID=$id;" does not seems to be complicated.

**Comment by jfilak** [comment]
It seems that the changes work fine. Here is the list of Fedora 23 Workstation bugs:
https://bugzilla.redhat.com/buglist.cgi?classification=Fedora&list_id=3953663&product=Fedora&query_format=advanced&status_whiteboard=%3BVARIANT_ID%3Dworkstation%3B&status_whiteboard_type=allwordssubstr&version=23

**Comment by xsuchy** [comment]
So I guess we can close it as done. Closing.
