### ISSUE TITLE
[RFE] Please bring back the ability to edit the reported data before submitting

### ISSUE THREAD

**Issue by alxpl** [abrt/abrt#997]
Hi,
I have been using abrt on Fedora 22 for a few days now and I could not find any way to edit my reports prior to submission on rhbz.
Call me paranoid, but I like to replace hostnames, user names, paths, MAC addresses of portable devices etc.. I was able to do that with abrt that shipped up to F21, but not any more (at least I haven't figured out how to accomplish that).
Please consider either restoring that functionality, or enhancing the mechanism that parses the files like forbidden_words.conf, so that certain words may be replaced before submitting the reports.
Something like:
```
word    substitute
alxpl    user
Big_Mac    hostname
00:24:1d:0d:3c:f0    aa:bb:cc:11:22:33
```
Thanks

**Comment by jfilak** [comment]
We don't call you paranoid, because editing of the problem data is a crucial feature that must work.

Just to be 100% sure we known what happened, you went through the reporting process with adding a comment, reviewing the data and filing bug in Red Hat Bugzilla and you could not edit your data in the reviewing step? Or did you try to modify the data directly in file system directory and it was not possible?

**Comment by alxpl** [comment]
I've had four bugs. For the first two, abrt generated and filed shortened reports and I was surprised that I wasn't asked to review anything. For the third one, it found that the problem had been reported already, so nothing was added to rhbz. When I dealt with the last one, I went through 3-4 screens and I cancelled the process, because I only got a dialog requesting consent to upload potentially private data, but at no point was I offered to review them. Would that have happened at a later step or do I need to configure something someplace? The configuration options are not very clear.

**Comment by alxpl** [comment]
This is really embarrassing, I got a kernel error and I decided to follow through with the report (though on MATE, so perhaps I need to take a better look at gnome-abrt when I'm using Gnome) and everything was there, just a little later in the reporting process.
I'm so sorry for the trouble!
